import {customSkins,drawMedia,PACK_LIMIT,PROJECT_LIMIT} from './media.js';
import {installMediaUI} from './media-ui.js';
import {drafts as draftStore} from './storage.js';
import {loadNative,nativeImage,drawNative} from './native-preview.js';
import {terrain,drawPiece,bounds,platformPolygon} from './pieces.js';
import {clone,createStagePack,validateStagePack,validateProject,moveSelection,interpolate,motion,History,pointIn,retimeMotion,mechanismCount,randomizeTargets,addPiece,appendTargetStop,setPlatformMotion,solidEdgeHandles,resizeSolidEdge} from './model.js?v=20261003-level-pack';
const $=id=>document.getElementById(id),canvas=$('scene'),ctx=canvas.getContext('2d');
let shipModel=null,olderDraft=null,nativeModels=[],actorModels={},additionModels={},additionCatalog={},placingStops=null;
let publishedProjects={},catalog=[],base=null,project=null,history=null,selection=null,artImage=null,housingImage=null,backgroundImage=null,pieceSprites={},view={x:0,y:0,scale:1},size={w:1,h:1},busy=false,local=false,frame=0,playing=false,last=0,drag=null,space=false,loadToken=0,saveTimer;
const skins=()=>[...(base?.pieces||[]),...customSkins(project||{})];
const mediaUI=installMediaUI({project:()=>project,base:()=>base,selection:()=>selection,commit,select,toast,add:id=>{selection=addPiece(project,base,id,project.spawn[0]+40,project.spawn[1]+60);}});
const storageKey=s=>'ttrc-editor-v1:'+s;
const el=(tag,text,cls)=>{const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e;};
function toast(text){$('toast').textContent=text;$('toast').hidden=false;clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('toast').hidden=true,5500);}
async function get(url){const r=await fetch(url);if(!r.ok)throw Error(`Could not load ${url.split('/').at(-1)} (${r.status}).`);return r.json();}
function image(src){return new Promise((resolve,reject)=>{const i=new Image();i.onload=()=>resolve(i);i.onerror=()=>reject(Error('Stage artwork could not load.'));i.src=src;});}
async function save(){if(!project)return;const p=project;try{await draftStore.set(storageKey(p.stage),JSON.stringify(p));localStorage.setItem('ttrc-editor-stage',p.stage);if(project===p)$('save-status').textContent='Saved in this browser';}catch{if(project===p)$('save-status').textContent='Not saved — export a backup';}}
function commit(){if(!project)return;history.push(project);save();renderUI();}
function fit(){if(!base)return;const [l,t,r,b]=base.artBounds;view.scale=Math.min((size.w-65)/(r-l),(size.h-65)/(t-b));view.x=size.w/2-(l+r)/2*view.scale;view.y=size.h/2+(t+b)/2*view.scale;draw();}
function screen([x,y]){return [view.x+x*view.scale,view.y-y*view.scale];}
function world(e){const r=canvas.getBoundingClientRect();return [(e.clientX-r.left-view.x)/view.scale,-(e.clientY-r.top-view.y)/view.scale];}
function snap(v){return $('snap').checked?Math.round(v/Number($('grid').value))*Number($('grid').value):Math.round(v*100)/100;}
function selected(type,index){return selection?.type===type&&selection.index===index;}
function objects(){if(!project)return [];return [...(base.shipPreview?[{type:'ship',index:0,name:base.shipPreview.name,kind:'native flight preview',icon:'◆'}]:[]),...project.targets.map((p,i)=>({type:'target',index:i,name:`Target ${i+1}`,kind:project.targetCycles.find(c=>c.target===i)?.kind||'static',icon:'◎'})),{type:'spawn',index:0,name:'Player spawn',kind:'start',icon:'⚑'},...project.solids.map((s,i)=>({type:'solid',index:i,name:skins().find(a=>a.id===s.asset)?.name||`Solid wall ${i+1}`,kind:`${s.points.length} vertices`,icon:'▰'})),...project.platforms.map((p,i)=>({type:'platform',index:i,name:skins().find(a=>a.id===project.platformAssets?.[i])?.name||`One-way platform ${i+1}`,kind:'collision',icon:'┄'})),...base.mechanisms.map((m,i)=>({type:'mechanism',index:i,name:m.name,kind:project.mechanisms[i].motion?.kind||m.kind,icon:'◇'})),...(project.nativeActors||[]).map((m,i)=>({type:'actor',index:i,name:m.name,kind:m.kind==='traffic'?'native route':m.kind===29?'native item':'native enemy',icon:'◆'})),...(project.decorations||[]).map((m,i)=>({type:'decoration',index:i,name:skins().find(c=>c.id===m.piece)?.name||'Decoration',kind:'no collision',icon:'▧'})),...project.additions.map((m,i)=>({type:'addition',index:i,name:m.name,kind:m.motion?.kind||m.kind,icon:'+'}))];}
function select(type,index){selection={type,index};renderUI();draw();}
function renderList(){const list=$('object-list');list.replaceChildren();const q=$('search').value.toLowerCase();const rows=objects().filter(o=>(o.name+' '+o.kind).toLowerCase().includes(q));$('object-count').textContent=objects().length;for(const o of rows){const b=el('button',undefined,'object'+(selected(o.type,o.index)?' selected':''));b.dataset.type=o.type;b.append(el('span',o.icon,'dot'),el('span',o.name),el('small',o.kind));b.onclick=()=>select(o.type,o.index);list.append(b);}if(!rows.length)list.append(el('p','No matching objects.','hint'));}
function field(grid,label,value,change,{min,max,step=.1,disabled=false,wide=false,options}={}){const wrap=el('label',undefined,'field'+(wide?' wide':''));wrap.append(el('span',label));let input;if(options){input=el('select');for(const [v,t]of options){const opt=el('option',t);opt.value=v;input.append(opt);}}else{input=el('input');input.type='number';input.step=step;if(min!==undefined)input.min=min;if(max!==undefined)input.max=max;}input.setAttribute('aria-label',label);input.value=value;input.disabled=disabled;input.addEventListener('change',()=>{const v=options?input.value:Number(input.value);if(!options&&(!Number.isFinite(v)||input.value==='')){toast('Enter a valid number.');input.value=value;return;}change(v);commit();});wrap.append(input);grid.append(wrap);return input;}
function textArea(parent,label,value,apply){const wrap=el('label',undefined,'field wide');wrap.append(el('span',label));const input=el('textarea');input.value=value;wrap.append(input);parent.append(wrap);const b=el('button','Apply coordinates');b.onclick=()=>{try{apply(input.value);commit();}catch(e){toast(e.message);}};parent.append(b);}
function routeId(){return selection?`${selection.type}:${selection.index}`:null;}
function routeVisible(){return $(selection?.type==='target'?'target-layer':'objects-layer').checked;}
function selectedRoute(){
 if(selection?.type==='target')return project.targetCycles.find(c=>c.target===selection.index);
 if(!['mechanism','addition'].includes(selection?.type))return null;
 const m=project[selection.type==='mechanism'?'mechanisms':'additions'][selection.index];
 if(!m?.motion||m.motion.kind==='static')return null;
 return {get kind(){return m.motion.kind;},get period(){return m.period;},get keys(){return m.motion.keys;},set keys(v){m.motion.keys=v;}};
}
function stopPlacement(){placingStops=null;renderUI();}
function syncPlacement(){
 if(placingStops!==null&&(placingStops!==routeId()||!selectedRoute()))placingStops=null;
 $('route-placement').hidden=placingStops===null;canvas.classList.toggle('placing-stops',placingStops!==null);
 if(placingStops!==null)$('route-instructions').textContent=`${objects().find(o=>selected(o.type,o.index))?.name||'Object'} · Click to add stops. Drag points to move them. Esc to finish.`;
}
function pauseMotion(){playing=false;frame=0;$('preview').textContent='▶ Preview motion';}
function stopHit(pt){const c=selectedRoute();if(!c||!routeVisible())return -1;let best=-1,distance=12/view.scale;for(let i=1;i<c.keys.length-1;i++){const k=c.keys[i],d=Math.hypot(pt[0]-k[1],pt[1]-k[2]);if(d<distance){best=i;distance=d;}}return best;}
function routeStops(fields,c){
 const tools=el('div',undefined,'route-actions'),place=el('button',placingStops===routeId()?'Finish placing stops':'Place stops on map');
 place.setAttribute('aria-pressed',String(placingStops===routeId()));place.className='primary';place.onclick=()=>{placingStops=placingStops===routeId()?null:routeId();pauseMotion();$(selection.type==='target'?'target-layer':'objects-layer').checked=true;renderUI();canvas.focus();};tools.append(place);
 const clear=el('button','Clear stops');clear.disabled=c.keys.length<=2;clear.onclick=()=>{c.keys=[[0,...c.keys[0].slice(1)],[c.period,...c.keys[0].slice(1)]];pauseMotion();commit();};tools.append(clear);fields.append(tools);
 fields.append(el('p','Click destinations in order. Adding on the map spaces stops evenly through the loop; you can adjust their times below. The route returns to its start.','hint'));

 fields.append(el('p',c.kind==='teleport'?'The object stays at each stop until the next stop’s frame, then teleports there.':'The object moves between stops. Add stops to shape its route.','hint'));
 c.keys.forEach((key,i)=>{const row=el('div',undefined,'field-grid waypoint');fields.append(row);const end=i===0||i===c.keys.length-1;field(row,`Stop ${i+1} frame`,key[0],v=>key[0]=v,{min:0,max:c.period,step:1,disabled:end});field(row,`Stop ${i+1} X`,key[1],v=>key[1]=v,{disabled:end});field(row,`Stop ${i+1} Y`,key[2],v=>key[2]=v,{disabled:end});if(!end){const del=el('button','Remove stop');del.onclick=()=>{c.keys.splice(i,1);commit();};row.append(del);}});
 const add=el('button','Add stop');add.disabled=c.keys.length>=65;add.onclick=()=>{const keys=c.keys;let i=1;for(let j=2;j<keys.length;j++)if(keys[j][0]-keys[j-1][0]>keys[i][0]-keys[i-1][0])i=j;const a=keys[i-1],b=keys[i];if(b[0]-a[0]<2)return toast('Lengthen the loop before adding another stop.');keys.splice(i,0,[Math.floor((a[0]+b[0])/2),(a[1]+b[1])/2,(a[2]+b[2])/2]);commit();};fields.append(add);
}

function inspect(){const fields=$('fields'),actions=$('selection-actions');fields.replaceChildren();actions.replaceChildren();const o=objects().find(o=>selected(o.type,o.index));$('selection-title').textContent=o?.name||'Select an object';$('selection-note').textContent='Click a target, wall or platform in the canvas.';if(!o)return;const {type,index}=o;const grid=el('div',undefined,'field-grid');fields.append(grid);
 const position=(p)=>{for(const [i,k]of ['X','Y'].entries())field(grid,k,p[i],v=>moveSelection(project,selection,i?0:v-p[0],i?v-p[1]:0,base));};
 if(type==='ship'){
  const preview=el('canvas');preview.width=240;preview.height=150;const [l,t,r,b]=shipModel.bounds,scale=Math.min(225/(r-l),135/(t-b));drawNative(preview.getContext('2d'),shipModel,0,0,([x,y])=>[120+(x-(l+r)/2)*scale,75-(y-(t+b)/2)*scale]);fields.append(preview);
  $('selection-note').textContent='Original Melee aircraft. This is a model preview, not its spawn position. Native flight paths and shots run in Dolphin.';
  return;
 }else if(type==='target'){
  position(project.targets[index]);let c=project.targetCycles.find(c=>c.target===index);
  field(grid,'Target behavior',c?.kind||'static',v=>{if(c&&v!=='static'){c.kind=v;return;}project.targetCycles=project.targetCycles.filter(c=>c.target!==index);if(v!=='static'){const [x,y]=project.targets[index];project.targetCycles.push({target:index,kind:v,period:240,keys:[[0,x,y],[120,x+30,y],[240,x,y]]});}},{wide:true,disabled:base.mechanisms.some(m=>m.opensTarget===index),options:[['static','Static'],['moving','Moving'],['teleport','Teleporting']]});
  if(c){field(grid,'Loop length (frames)',c.period,v=>{v=Math.round(v);const ratio=v/c.period;c.keys=c.keys.map(([f,x,y])=>[Math.round(f*ratio),x,y]);c.period=v;},{min:2,max:3600,step:1});routeStops(fields,c);const advanced=el('details');advanced.append(el('summary','Edit raw keyframes'));fields.append(advanced);textArea(advanced,'Keyframes: frame, X, Y (one per line)',c.keys.map(k=>k.join(', ')).join('\n'),s=>{const keys=parseRows(s,3);if(keys.some(k=>!Number.isInteger(k[0])))throw Error('Frames must be whole numbers.');c.keys=keys;});$('selection-note').textContent='Moving paths interpolate linearly. Teleports hold each point until the next keyframe. Start and finish the loop at the target position.';}else $('selection-note').textContent=base.routes[index]?.hint||'Target positions and animations compile directly into the stage.';
 }else if(type==='actor'){const m=project.nativeActors[index];position([m.x,m.y]);$('selection-note').textContent=m.kind===29?'Original Melee Warp Star. Pick it up with A to launch, then steer left or right during the descent. Falls onto the terrain and returns when you restart the level.':m.kind==='traffic'?'Moves the complete Onett traffic lane. Cars retain their native route, speed and attacks. The preview marks the lane origin.':'Spawn position for the original Melee actor. AI and animation run in Dolphin; this preview shows its bind pose.';
 }else if(type==='spawn'){position(project.spawn);$('selection-note').textContent='Place the spawn just above a safe floor. The editor checks wall overlap; Dolphin checks the actual landing.';}
 else if(type==='solid'){
  const s=project.solids[index],p=s.points;position([Math.min(...p.map(v=>v[0])),Math.min(...p.map(v=>v[1]))]);
  textArea(fields,'Collision vertices: X, Y (clockwise)',p.map(k=>k.join(', ')).join('\n'),t=>{const rows=parseRows(t,2);if(rows.length<4||rows.length>24)throw Error('Use 4–24 vertices.');s.points=rows;});
  $('selection-note').textContent='This block’s texture and solid collision move together. Drag a round side handle to resize both corners together. Square corner handles reshape the outline freely.';
 }else if(type==='decoration'){
  const m=project.decorations[index];position([m.x,m.y]);field(grid,'Width',m.width,v=>m.width=v,{min:2,max:800});field(grid,'Height',m.height,v=>m.height=v,{min:2,max:800});$('selection-note').textContent='A textured decoration with no solid collision.';
 }else if(type==='platform'){
  const p=project.platforms[index];position(p);field(grid,'Width',p[2],v=>p[2]=v,{min:2,max:800});$('selection-note').textContent='Jump through from below and land on top. Moving or resizing carries the textured ledge with it.';
 }else{
  const original=type==='mechanism'?base.mechanisms[index]:project.additions[index].kind==='template'?base.mechanisms[project.additions[index].template]:null,m=type==='mechanism'?project.mechanisms[index]:project.additions[index];position([m.x,m.y]);
  const kind=original?.kind||m.kind;
  if(type==='addition'&&m.kind==='bumper'){
   field(grid,'Width',m.width,v=>{m.height??=m.width;m.width=v;},{min:.1});
   field(grid,'Height',m.height??m.width,v=>m.height=v,{min:.1});
   grid.append(el('p','Original red/yellow animation · 10% damage.'));
  }
  if(kind==='boost'){
   const speed=m.impulseX??original.impulseX;field(grid,'Direction',speed<0?'left':'right',v=>m.impulseX=(v==='left'?-1:1)*Math.abs(m.impulseX??original.impulseX),{options:[['right','Right →'],['left','Left ←']]});field(grid,'Boost speed',Math.abs(speed),v=>m.impulseX=Math.sign(m.impulseX??original.impulseX)*v,{min:1,max:12});$('selection-note').textContent='Falcon’s textured speed arrow. Grounded contact gives a horizontal impulse, without damage. Place it flush with a floor.';
  }else{
   if(original?.opensTarget===undefined)field(grid,'Movement',m.motion?.kind||'authored',v=>{setPlatformMotion(m,original,v);pauseMotion();},{wide:true,options:[['authored','Original motion'],['static','Static'],['moving','Moving'],['teleport','Teleporting']]});
   const custom=!!m.motion;
   if(custom){field(grid,'Loop length (frames)',m.period,v=>retimeMotion(m,Math.round(v)),{min:60,max:3600,step:1});if(m.motion.kind!=='static')routeStops(fields,selectedRoute());}

   if(!custom){for(const [key,label,min,max]of [['dx','Travel X',-1500,1500],['dy','Travel Y',-1500,1500],['period','Period (frames)',60,3600],['hold','End hold (frames)',0,900]])field(grid,label,m[key],v=>key==='period'?retimeMotion(m,v):m[key]=v,{min,max,step:['period','hold'].includes(key)?1:.1,disabled:!!original?.[key==='dx'?'xKeys':key==='dy'?'yKeys':'__none']});
   if(type!=='addition')field(grid,'Rotation (degrees)',m.angle,v=>m.angle=v,{min:-180,max:180,disabled:!!original.angleKeys});}
   $('selection-note').textContent=custom?'Place or drag route points on the map. The model, collision and contact damage follow the same route.':original?.xKeys||original?.angleKeys?'Original authored keyframes are preserved. You can offset the object and retime its loop. Native models and damage behavior remain attached.':'Original textured model and behavior are preserved.';
  }
  if(type==='addition'&&m.kind!=='template'&&m.kind!=='bumper')field(grid,'Width',m.width,v=>m.width=v,{min:4,max:kind==='platform'?800:160});
  if(type==='addition'&&m.kind==='bumper')$('selection-note').textContent='Drag a round side handle or change Width and Height to resize the model and its collision together.';
 }
 if(type==='decoration'||type==='solid'||type==='addition'||type==='platform'||type==='actor'&&project.nativeActors[index].kind!=='traffic'){const del=el('button','Delete');del.onclick=()=>{project[type==='decoration'?'decorations':type==='solid'?'solids':type==='addition'?'additions':type==='actor'?'nativeActors':'platforms'].splice(index,1);if(type==='platform'&&project.platformAssets)project.platformAssets.splice(index,1);selection=null;commit();};actions.append(del);}
 if(type==='decoration'||type==='solid'||type==='platform'||type==='addition'||type==='actor'&&project.nativeActors[index].kind!=='traffic'){const b=el('button','Duplicate');b.onclick=()=>{if(type==='addition'&&project.mechanisms.length+project.additions.length>=10)return toast('The stage already uses all 10 mechanism groups.');const list=project[type==='decoration'?'decorations':type==='addition'?'additions':type==='solid'?'solids':type==='actor'?'nativeActors':'platforms'];if(type==='actor'&&list.length>=16)return toast('At most 16 native actors.');const copied=clone(list[index]);if(type==='solid')delete copied.source;list.push(copied);if(type==='platform')project.platformAssets.push(project.platformAssets[index]);selection={type,index:list.length-1};moveSelection(project,selection,10,10,base);commit();};actions.append(b);}
 
}
function parseRows(text,count){const rows=text.trim().split('\n').map(line=>line.split(',').map(s=>Number(s.trim())));if(rows.some(r=>r.length!==count||r.some(v=>!Number.isFinite(v))))throw Error(`Each row needs ${count} numeric values, separated by commas.`);return rows;}
function checks(){const {errors,warnings}=validateProject(project,base);$('validation-count').textContent=errors.length?`${errors.length} ${errors.length===1?'issue':'issues'}`:'Ready to test';$('validation-list').replaceChildren(...(errors.length?errors.map(s=>el('p',s,'issue error')):[el('p','Ten targets · valid positions · compatible project','issue good')]),...warnings.map(s=>el('p',s,'issue')));$('test').disabled=busy||!!errors.length;return errors;}
function renderUI(){if(!project)return;syncPlacement();$('frame').max=Math.max(1200,...project.mechanisms.map(m=>m.period),...project.additions.map(m=>m.period),...project.targetCycles.map(c=>c.period),...(project.media||[]).map(m=>m.frames.length*m.frameTicks));$('name').value=project.name;$('undo').disabled=history.index===0;$('redo').disabled=history.index===history.items.length-1;renderList();inspect();checks();mediaUI.render();const full=project.mechanisms.length+project.additions.length>=10;$('add-platform').disabled=full||base.stage==='Gw';$('add-bumper').disabled=full||base.stage==='Gw';$('add-solid').disabled=project.solids.length>=64||!base.pieces.some(a=>a.kind==='solid');$('add-floor').disabled=project.platforms.length>=128||!base.pieces.some(a=>a.kind==='platform');for(const id of ['add-boost-right','add-boost-left'])$(id).disabled=full||['Gw','Ns','Ic','Sk'].includes(base.stage)||[...base.mechanisms,...project.additions].filter(m=>m.kind==='boost').length>=8;$('randomize').disabled=false;draw();}
async function load(stage,imported){placingStops=null;syncPlacement();const token=++loadToken;$('loading').hidden=false;await save();$('loading').querySelector('p').textContent='Loading stage…';$('retry').hidden=true;$('test').disabled=true;try{const data=await get(`/editor/data/${stage}.json`),entry=catalog.find(c=>c.stage===stage);let next=clone(publishedProjects[stage]||data.project);if(imported){try{const old=await draftStore.get(storageKey(stage));if(old&&old!==JSON.stringify(imported)){olderDraft=old;await draftStore.set(storageKey(stage)+':older',old);$('recover').hidden=false;}}catch{}const report=validateProject(imported,data);if(report.errors.length)throw Error(report.errors.join(' '));next=clone(imported);}else{try{const raw=await draftStore.get(storageKey(stage));if(raw){const saved=JSON.parse(raw);if(saved.revision===data.project.revision&&saved.stage===stage)next=saved;else {olderDraft=raw;await draftStore.set(storageKey(stage)+':older',raw);$('recover').hidden=false;toast('The older draft was backed up. Use Export older draft to keep a file.');}}}catch{toast('Saved draft could not be read; the original stage was opened.');}}
 for(const m of next.additions||[])if(m.kind==='bumper'&&/^(?:(?:Red|Yellow) )?Fox bumper$/i.test(m.name))m.name='Bumper';
 const [im,housing,bg,models,actors,added,sprites,ship]=await Promise.all([entry.image?image(entry.image):null,data.housing?image(data.housing.image):null,data.background?image(data.background):null,Promise.all((data.modelPreviews||[]).map(loadNative)),Promise.all(Object.entries(data.nativeActorModels||{}).map(async([k,url])=>[k,await loadNative(url)])),Promise.all(Object.entries({...additionCatalog[stage],bumper:'/editor/data/models/Fx-add-bumper.json','bumper-red':'/editor/data/models/Fx-add-bumper-red.json'}).map(async([k,url])=>[k,await loadNative(url)])),Promise.all((data.pieces||[]).filter(p=>p.sprite).map(async p=>[p.sprite,await image(p.spriteImage)])),data.shipPreview?loadNative(data.shipPreview.model):null]);if(token!==loadToken)return;base=data;shipModel=ship;project=next;artImage=im;housingImage=housing;backgroundImage=bg;nativeModels=models;actorModels=Object.fromEntries(actors);additionModels=Object.fromEntries(added);pieceSprites=Object.fromEntries(sprites);selection=null;history=new History(project);frame=0;playing=false;$('preview').textContent='▶ Preview motion';$('stage').value=stage;$('stage-note').textContent=`${base.name} · ${base.scale}× native scale`;try{const backup=await draftStore.get(storageKey(stage)+':older');if(backup){olderDraft=backup;$('recover').hidden=false;}}catch{}$('native-list').replaceChildren(...(base.sources?.length?base.sources.map(s=>el('p',`${s.name||s.actor||s.source||'Native actor'} — ${s.implementation||'Original Melee behavior'}`)):[el('p','Authored terrain and stage mechanisms.')]));$('route-notes').replaceChildren(el('p',`Jump apex: ${Number(base.movement.ballisticJumpApex).toFixed(1)} native units · air speed ${Number(base.movement.airSpeed).toFixed(2)}. Special moves and multi-jumps are not simulated.`));const list=el('ol');for(const r of base.routes)list.append(el('li',r.hint||r.move||'Authored target'));$('route-notes').append(list);renderPalette();fit();renderUI();await save();if(token===loadToken)$('loading').hidden=true;}catch(e){if(token!==loadToken)return;$('loading').querySelector('p').textContent=e.message;$('retry').hidden=false;toast(e.message);}}
function drawPath(points,color,width=1,fill=null,dashed=false){ctx.beginPath();points.forEach((p,i)=>{const [x,y]=screen(p);i?ctx.lineTo(x,y):ctx.moveTo(x,y);});if(fill){ctx.closePath();ctx.fillStyle=fill;ctx.fill();}ctx.strokeStyle=color;ctx.lineWidth=width;ctx.setLineDash(dashed?[5,4]:[]);ctx.stroke();ctx.setLineDash([]);}
function draw(){ctx.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0);ctx.clearRect(0,0,size.w,size.h);if(!project)return;const [l,t,r,b]=base.artBounds;
 ctx.save();if(base.floorVoids?.length){ctx.fillStyle=base.voidColor;for(const [a,b,c,d]of base.floorVoids){const [x,y]=screen([a,d]);ctx.fillRect(x,y,(c-a)*view.scale,(d-b)*view.scale);}ctx.beginPath();ctx.rect(0,0,size.w,size.h);for(const [a,b,c,d]of base.floorVoids){const [x,y]=screen([a,d]);ctx.rect(x,y,(c-a)*view.scale,(d-b)*view.scale);}ctx.clip('evenodd');}
 if($('art-layer').checked){if(base.modular){const [bl,bt,br,bb]=base.backgroundBounds||base.artBounds,[bx,by]=screen([bl,bt]);if(project.background){const bg=project.background,[a,t,c,b]=bg.bounds;drawMedia(ctx,project.media.find(m=>m.id===bg.media),[[a,t],[c,t],[c,b],[a,b]],screen,frame);}else if(backgroundImage)ctx.drawImage(backgroundImage,bx,by,(br-bl)*view.scale,(bt-bb)*view.scale);else for(const tri of base.illustration||[])drawPath(tri.map(v=>v.slice(0,2)),tri[0][3],.1,tri[0][3]);for(const d of project.decorations||[]){const c=skins().find(c=>c.id===d.piece);drawMedia(ctx,project.media.find(m=>m.id===c.media),[[d.x,d.y],[d.x+d.width,d.y],[d.x+d.width,d.y-d.height],[d.x,d.y-d.height]],screen,frame,c.mapping,c.width);}terrain(ctx,base,project,artImage,screen,pieceSprites,frame);if(housingImage){for(const s of project.solids.filter(s=>s.asset===base.housing?.asset&&base.stage==='Pk')){const [sl,st,sr,sb]=bounds(s.points),[x,y]=screen([sl,st]),[sx,sy,rx,ry]=base.housing.source;ctx.save();ctx.beginPath();s.points.forEach((p,i)=>{const [px,py]=screen(p);i?ctx.lineTo(px,py):ctx.moveTo(px,py)});ctx.closePath();ctx.clip();ctx.drawImage(housingImage,sx,sy,rx-sx,ry-sy,x,y,(sr-sl)*view.scale,(st-sb)*view.scale);ctx.restore();}}}else if(artImage){const [x,y]=screen([l,t]);ctx.globalAlpha=$('collision-layer').checked?.78:1;ctx.drawImage(artImage,x,y,(r-l)*view.scale,(t-b)*view.scale);ctx.globalAlpha=1;for(const c of base.platformCopies){const [sx,sy,sr,sb]=c.sourcePixels,[cx,cy,w]=c.surface,[px,py]=screen([cx,cy]);ctx.drawImage(artImage,sx/base.imageSize[0]*artImage.width,sy/base.imageSize[1]*artImage.height,(sr-sx)/base.imageSize[0]*artImage.width,(sb-sy)/base.imageSize[1]*artImage.height,px,py,w*view.scale,c.height*view.scale);}if(housingImage){const [sx,sy,sr,sb]=base.housing.source,[cx,cy,w,h]=base.housing.rect,[px,py]=screen([cx,cy+h]);ctx.drawImage(housingImage,sx,sy,sr-sx,sb-sy,px,py,w*view.scale,h*view.scale);}}else for(const tri of base.illustration||[])drawPath(tri.map(v=>v.slice(0,2)),tri[0][3],.1,tri[0][3]);}
 ctx.restore();
 if($('snap').checked&&view.scale>1.5){const step=Number($('grid').value)*5;ctx.globalAlpha=.14;for(let x=Math.ceil(l/step)*step;x<r;x+=step)drawPath([[x,b],[x,t]],'#b9cbd8',.5);for(let y=Math.ceil(b/step)*step;y<t;y+=step)drawPath([[l,y],[r,y]],'#b9cbd8',.5);ctx.globalAlpha=1;}
 if($('collision-layer').checked){project.solids.forEach((s,i)=>{drawPath([...s.points,s.points[0]],selected('solid',i)?'#eaff99':'#e3ad75',selected('solid',i)?2.5:1.4,selected('solid',i)?'#cbe67828':'#dd9d5622');});project.platforms.forEach(([x,y,w],i)=>drawPath([[x,y],[x+w,y]],selected('platform',i)?'#eaff99':'#76ddd1',selected('platform',i)?4:2,null,true));}
 if($('objects-layer').checked&&shipModel&&base.shipPreview){const [x,y]=base.shipPreview.anchor;drawNative(ctx,shipModel,x,y,screen);const [px,py]=screen([x,y+shipModel.bounds[1]+5]);ctx.fillStyle='#e4ebff';ctx.font='11px sans-serif';ctx.fillText(base.shipPreview.name+' · model preview',px,py);}
 if($('objects-layer').checked){for(const type of ['mechanism','addition'])for(const [i,m]of project[type==='mechanism'?'mechanisms':'additions'].entries()){const original=type==='mechanism'?base.mechanisms[i]:m.kind==='template'?base.mechanisms[m.template]:m;const route=Array.from({length:49},(_,n)=>motion(m,original,n*m.period/48));drawPath(route,'#c6b7ff77',1,null,true);const [x,y]=motion(m,original,frame),w=original.width,h=original.height||7;const generic=type==='addition'&&m.kind!=='template',key=m.kind==='boost'&&m.impulseX<0?'boost-left':m.kind,model=type==='mechanism'?nativeModels[i]:m.kind==='template'?nativeModels[m.template]:additionModels[key];if(model){const sx=generic?m.width/model.width:1,sy=generic&&m.kind==='bumper'?(m.height??m.width)/model.width:generic&&model.scaleYWithWidth?sx:1;ctx.save();if(original.entity==='plant'&&$('art-layer').checked)for(const solid of project.solids){ctx.beginPath();ctx.rect(0,0,size.w,size.h);solid.points.forEach((p,j)=>j?ctx.lineTo(...screen(p)):ctx.moveTo(...screen(p)));ctx.closePath();ctx.clip('evenodd');}drawNative(ctx,model,x,y,screen,frame,sx,sy,m.period,model.rolling?m.motion?.kind==='teleport'?0:-(x-m.x)/model.rolling.radius:null);ctx.restore();}
 let poly=original.outline||original.floorOutline||[[0,0],[w,0],[w,-(original.kind==='bumper'?(original.height??w):h)],[0,-(original.kind==='bumper'?(original.height??w):h)]];
 let angle=0;if(!m.motion&&original.angleKeys)angle=interpolate(original.angleKeys.map(([f,v])=>[f*m.period/original.period,v]),frame%m.period);else if(!m.motion&&m.angle){const p=m.period,hold=m.hold;angle=interpolate([[0,0],[hold,0],[p/2,m.angle*Math.PI/180],[p/2+hold,m.angle*Math.PI/180],[p,0]],frame%p);}
 poly=poly.map(([px,py])=>[x+px*Math.cos(angle)-py*Math.sin(angle),y+px*Math.sin(angle)+py*Math.cos(angle)]);drawPath([...poly,poly[0]],selected(type,i)?'#eaff99':'#c6b7ff',selected(type,i)?3:1.5,model?null:'#8b70c033');const [px,py]=screen([x,y]);ctx.font='10px system-ui';ctx.fillStyle='#e2d9ff';ctx.fillText(original.name||m.name,px,py-7);}}
 if($('objects-layer').checked)for(const [i,a]of (project.nativeActors||[]).entries()){const model=actorModels[a.kind];if(model){drawNative(ctx,model,a.x,a.y,screen,frame);const [l,t,r,b]=model.bounds;drawPath([[a.x+l,a.y+b],[a.x+r,a.y+b],[a.x+r,a.y+t],[a.x+l,a.y+t],[a.x+l,a.y+b]],selected('actor',i)?'#eaff99':'#aabbcc66',1);}}
 if($('target-layer').checked){project.targets.forEach((p,i)=>{const c=project.targetCycles.find(c=>c.target===i);let pt=p;if(c){const f=frame%c.period;pt=[interpolate(c.keys.map(k=>[k[0],k[1]]),f,c.kind==='teleport'),interpolate(c.keys.map(k=>[k[0],k[2]]),f,c.kind==='teleport')];drawPath(c.keys.map(k=>k.slice(1)),'#ff899977',1,null,c.kind==='teleport');}const [x,y]=screen(pt),radius=Math.max(6,6*view.scale);for(const [mult,color]of [[1,'#ff657d'],[.7,'#fff2e9'],[.45,'#e8415d'],[.2,'#fff2e9']]){ctx.beginPath();ctx.arc(x,y,radius*mult,0,Math.PI*2);ctx.fillStyle=color;ctx.fill();}if(selected('target',i)){ctx.beginPath();ctx.arc(x,y,radius+4,0,Math.PI*2);ctx.strokeStyle='#eaff99';ctx.lineWidth=2;ctx.stroke();}ctx.font='bold 10px system-ui';ctx.fillStyle='white';ctx.fillText(String(i+1),x+radius+4,y+3);});const [x,y]=screen(project.spawn);ctx.fillStyle='#a9ef90';ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x-7,y-13);ctx.lineTo(x+7,y-13);ctx.fill();ctx.font='bold 11px system-ui';ctx.fillText('P1',x-7,y-18);}
 if(selection?.type==='solid'&&($('art-layer').checked||$('collision-layer').checked)){
  const points=project.solids[selection.index].points;
  if(!$('collision-layer').checked)drawPath([...points,points[0]],'#eaff99',2);
  for(const pt of points){const [x,y]=screen(pt);ctx.fillStyle='#eaff99';ctx.fillRect(x-4,y-4,8,8);}
 }
 for(const h of resizeHandles()){const [x,y]=screen(h.point);ctx.beginPath();ctx.arc(x,y,6,0,Math.PI*2);ctx.fillStyle='#192620';ctx.fill();ctx.strokeStyle='#eaff99';ctx.lineWidth=2;ctx.stroke();ctx.beginPath();ctx.moveTo(x-(h.axis===0?3:0),y-(h.axis===1?3:0));ctx.lineTo(x+(h.axis===0?3:0),y+(h.axis===1?3:0));ctx.stroke();}
 const route=selectedRoute();if(route&&routeVisible()){
  drawPath(route.keys.map(k=>k.slice(1)),'#d9ff73',2,null,route.kind==='teleport');
  route.keys.slice(0,-1).forEach((k,i)=>{const [x,y]=screen(k.slice(1));ctx.beginPath();ctx.arc(x,y,i?10:6,0,Math.PI*2);ctx.fillStyle='#17211c';ctx.fill();ctx.strokeStyle='#d9ff73';ctx.lineWidth=2;ctx.stroke();ctx.font='bold 11px system-ui';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillStyle='#d9ff73';ctx.fillText(i?String(i+1):'1 ↺',x,i?y:y-15);ctx.textAlign='start';ctx.textBaseline='alphabetic';});
 }
 $('zoom').textContent=Math.round(view.scale*100)+'%';$('frame-label').textContent=`${Math.round(frame)}f · ${(frame/60).toFixed(2)}s`;$('frame').value=frame;
}
function hit(pt){const tol=10/view.scale;if(shipModel&&base.shipPreview&&$('objects-layer').checked){const [x,y]=base.shipPreview.anchor,[l,t,r,b]=shipModel.bounds;if(pt[0]>=x+l&&pt[0]<=x+r&&pt[1]>=y+b&&pt[1]<=y+t)return {type:'ship',index:0};}if($('objects-layer').checked)for(const [i,a]of (project.nativeActors||[]).entries()){const model=actorModels[a.kind];if(model){const [l,t,r,b]=model.bounds;if(pt[0]>=a.x+l&&pt[0]<=a.x+r&&pt[1]>=a.y+b&&pt[1]<=a.y+t)return {type:'actor',index:i};}}if($('target-layer').checked){for(let i=0;i<10;i++)if(Math.hypot(pt[0]-project.targets[i][0],pt[1]-project.targets[i][1])<tol+6)return {type:'target',index:i};if(Math.hypot(pt[0]-project.spawn[0],pt[1]-project.spawn[1])<tol+5)return {type:'spawn',index:0};}if($('objects-layer').checked)for(const type of ['addition','mechanism']){const arr=project[type==='addition'?'additions':'mechanisms'];for(let i=arr.length-1;i>=0;i--){const m=arr[i],o=type==='addition'?m:base.mechanisms[i];if(pt[0]>=m.x-tol&&pt[0]<=m.x+o.width+tol&&pt[1]<=m.y+tol&&pt[1]>=m.y-(o.height||o.width||7)-tol)return {type,index:i};}}if($('collision-layer').checked||base.modular&&$('art-layer').checked){for(let i=project.platforms.length-1;i>=0;i--){const [x,y,w]=project.platforms[i];if(pt[0]>=x&&pt[0]<=x+w&&Math.abs(pt[1]-y)<tol)return {type:'platform',index:i};}for(let i=project.solids.length-1;i>=0;i--)if(pointIn(pt,project.solids[i].points))return {type:'solid',index:i};}if($('art-layer').checked)for(let i=(project.decorations||[]).length-1;i>=0;i--){const d=project.decorations[i];if(pt[0]>=d.x&&pt[0]<=d.x+d.width&&pt[1]<=d.y&&pt[1]>=d.y-d.height)return {type:'decoration',index:i};}return null;}
function resizeHandles(){
 if(selection?.type==='addition'&&$('objects-layer').checked){const m=project.additions[selection.index];if(m.kind==='bumper'){const [x,y]=motion(m,m,frame);const h=m.height??m.width;return [{point:[x+m.width,y-h/2],axis:0,bumper:true},{point:[x+m.width/2,y-h],axis:1,bumper:true}];}}
 return selection?.type==='solid'&&($('art-layer').checked||$('collision-layer').checked)?solidEdgeHandles(project.solids[selection.index].points).filter(h=>h.length*view.scale>=24):[];
}
function edgeHit(pt){return resizeHandles().find(h=>Math.hypot(h.point[0]-pt[0],h.point[1]-pt[1])*view.scale<9);}
canvas.onpointerdown=e=>{
 if(!project||busy||!$('loading').hidden)return;canvas.focus();const pt=world(e);
 if(space||e.button===1){e.preventDefault();drag={pan:true,x:e.clientX,y:e.clientY,view:{...view}};canvas.setPointerCapture(e.pointerId);return;}
 if(e.button!==0)return;
 if(playing||frame){pauseMotion();draw();}
 const waypoint=stopHit(pt);
 if(waypoint>=0){drag={start:pt,before:clone(project),waypoint,target:selection.index,vertex:-1,changed:false};canvas.setPointerCapture(e.pointerId);return;}
 if(placingStops!==null){
  const [l,t,r,b]=base.artBounds,point=pt.map(snap);if(point[0]<=l||point[0]>=r||point[1]<=b||point[1]>=t)return toast('Place the stop inside the stage.');
  try{appendTargetStop(selectedRoute(),point);commit();}catch(error){toast(error.message);}return;
 }
 let vertex=-1;if(selection?.type==='solid')vertex=project.solids[selection.index].points.findIndex(p=>Math.hypot(p[0]-pt[0],p[1]-pt[1])<8/view.scale);
 const edge=vertex<0?edgeHit(pt):undefined;
 const found=vertex>=0||edge?selection:hit(pt);if(!found){selection=null;renderUI();return;}selection=found;renderUI();if(found.type==='ship')return;drag={start:pt,before:clone(project),vertex,edge,changed:false};canvas.setPointerCapture(e.pointerId);
};
canvas.onpointermove=e=>{
 if(!project)return;const pt=world(e);$('coordinates').textContent=`X ${pt[0].toFixed(1)}  Y ${pt[1].toFixed(1)}`;
 if(!drag){const edge=edgeHit(pt);canvas.classList.toggle('over-stop',stopHit(pt)>=0);canvas.style.cursor=edge?(edge.axis===0?'ew-resize':'ns-resize'):'';canvas.title=edge?'Drag to resize this side':'';return;}
 if(drag.pan){view.x=drag.view.x+e.clientX-drag.x;view.y=drag.view.y+e.clientY-drag.y;draw();return;}
 project=clone(drag.before);
 if(drag.waypoint!==undefined){const c=selectedRoute(),k=c.keys[drag.waypoint];k[1]=snap(pt[0]);k[2]=snap(pt[1]);}
 else if(drag.edge?.bumper){const m=project.additions[selection.index];m.height??=m.width;if(drag.edge.axis===0)m.width=Math.max(.1,m.width+snap(pt[0]-drag.start[0]));else m.height=Math.max(.1,m.height-snap(pt[1]-drag.start[1]));}
 else if(drag.edge){const solid=project.solids[selection.index];solid.points=resizeSolidEdge(solid.points,drag.edge.index,snap(pt[drag.edge.axis]-drag.start[drag.edge.axis]));}
 else if(drag.vertex>=0)project.solids[selection.index].points[drag.vertex]=pt.map(snap);
 else moveSelection(project,selection,snap(pt[0]-drag.start[0]),snap(pt[1]-drag.start[1]),base);
 drag.changed=true;draw();
};
const release=()=>{if(drag?.changed)commit();drag=null;};canvas.onpointerup=release;canvas.onpointercancel=()=>{if(drag?.before)project=drag.before;drag=null;renderUI();};
$('route-done').onclick=stopPlacement;
canvas.addEventListener('wheel',e=>{e.preventDefault();const p=world(e),r=canvas.getBoundingClientRect();view.scale=Math.max(.1,Math.min(12,view.scale*Math.exp(-e.deltaY*.001)));view.x=e.clientX-r.left-p[0]*view.scale;view.y=e.clientY-r.top+p[1]*view.scale;draw();},{passive:false});
new ResizeObserver(()=>{const r=$('canvas-wrap').getBoundingClientRect();size={w:r.width,h:r.height};canvas.width=Math.round(size.w*devicePixelRatio);canvas.height=Math.round(size.h*devicePixelRatio);if(base)fit();}).observe($('canvas-wrap'));
$('stage').onchange=()=>load($('stage').value);$('retry').onclick=()=>load($('stage').value);$('name').onchange=()=>{if(project){project.name=$('name').value;commit();}};$('search').oninput=renderList;
for(const id of ['art-layer','collision-layer','target-layer','objects-layer','snap','grid'])$(id).onchange=draw;
$('fit').onclick=fit;for(const [id,factor]of [['zoom-in',1.25],['zoom-out',.8]])$(id).onclick=()=>{view.x=size.w/2+(view.x-size.w/2)*factor;view.y=size.h/2+(view.y-size.h/2)*factor;view.scale*=factor;draw();};
$('undo').onclick=()=>{project=history.undo();selection=null;save();renderUI();};$('redo').onclick=()=>{project=history.redo();selection=null;save();renderUI();};
$('reset').onclick=()=>{if(project)$('confirm').showModal();};$('confirm').onclose=()=>{if($('confirm').returnValue==='reset'){project=clone(base.project);selection=null;commit();}};
function add(kind){if(!project||mechanismCount(project)>=10)return;project.additions.push({kind,name:kind==='platform'?'New moving platform':'Bumper',x:snap(project.spawn[0]+30),y:snap(project.spawn[1]+20),width:kind==='platform'?32:16,dx:kind==='platform'?40:0,dy:0,period:240,hold:30});selection={type:'addition',index:project.additions.length-1};commit();}
$('add-solid').onclick=()=>{const a=base.pieces.find(a=>a.id==='basic-brick')||base.pieces.find(a=>a.kind==='solid');if(a){selection=addPiece(project,base,a.id,project.spawn[0]+35,project.spawn[1]+35);commit();}};
$('add-floor').onclick=()=>{const a=base.pieces.find(a=>a.id==='basic-wood')||base.pieces.find(a=>a.kind==='platform');if(a){selection=addPiece(project,base,a.id,project.spawn[0]+35,project.spawn[1]+35);commit();}};
function renderPalette(){
 const list=$('piece-library');list.replaceChildren();
 for(const a of [...(base.pieces||[])].sort((a,b)=>Number(b.id.startsWith('basic-'))-Number(a.id.startsWith('basic-')))){
  const button=el('button',undefined,'piece-card'),thumb=el('canvas');thumb.width=180;thumb.height=100;const c=thumb.getContext('2d'),[l,t,r,b]=bounds(a.points),scale=Math.min(164/(r-l),84/(t-b));
  const map=([x,y])=>[90+(x-(l+r)/2)*scale,50-(y-(t+b)/2)*scale];
  drawPiece(c,a.sprite?pieceSprites[a.sprite]:artImage,a.sprite?[0,0,1,-1]:a.sourceRect,a.points,a.sprite?[0,0,1,-1]:base.artBounds,map);
  button.append(thumb,el('span',a.name),el('small',a.kind==='solid'?'Solid block':'One-way platform'));button.title='Add '+a.name;button.onclick=()=>{try{selection=addPiece(project,base,a.id,project.spawn[0]+40,project.spawn[1]+45);commit();}catch(e){toast(e.message);}};list.append(button);
 }
 for(const [kind,model]of Object.entries(actorModels)){const a=base.project.nativeActors.find(a=>String(a.kind)===kind)||(kind==='29'?{kind:29,name:'Warp Star'}:null),button=el('button',undefined,'piece-card'),thumb=el('canvas');thumb.width=180;thumb.height=100;const [l,t,r,b]=model.bounds,scale=Math.min(170/(r-l),90/(t-b));drawNative(thumb.getContext('2d'),model,0,0,([x,y])=>[90+(x-(l+r)/2)*scale,50-(y-(t+b)/2)*scale]);button.append(thumb,el('span',a.name),el('small',kind==='traffic'?'Select route anchor':kind==='29'?'Add native item':'Add native enemy'));button.onclick=()=>{if(kind==='traffic'){selection={type:'actor',index:project.nativeActors.findIndex(a=>a.kind==='traffic')};renderUI();return;}if(project.nativeActors.length>=16)return toast('At most 16 native actors.');project.nativeActors.push({...a,x:project.spawn[0]+40,y:project.spawn[1]+25});selection={type:'actor',index:project.nativeActors.length-1};commit();};list.append(button);}
 for(const [index,m]of base.mechanisms.entries()){
  if(m.opensTarget!==undefined||m.kind==='boost')continue;
  const button=el('button',undefined,'piece-card'),thumb=el('canvas');thumb.width=180;thumb.height=100;const c=thumb.getContext('2d'),model=nativeModels[index];if(model){const [l,t,r,b]=model.bounds,scale=Math.min(170/(r-l),90/(t-b));drawNative(c,model,0,0,([x,y])=>[90+(x-(l+r)/2)*scale,50-(y-(t+b)/2)*scale]);}button.append(thumb,el('span',m.name),el('small','Original '+m.kind));button.onclick=()=>{if(mechanismCount(project)>=10)return toast('At most 10 native mechanism groups.');project.additions.push({kind:'template',template:index,name:m.name,x:m.x+20,y:m.y+20,width:m.width,dx:m.dx,dy:m.dy,period:m.period,hold:m.hold});selection={type:'addition',index:project.additions.length-1};commit();};list.append(button);
 }
}
function addBoost(direction){if(!project||mechanismCount(project)>=10)return;project.additions.push({kind:'boost',name:direction>0?'Rightward speed boost':'Leftward speed boost',x:snap(project.spawn[0]+30),y:snap(project.spawn[1]-2),width:46,dx:0,dy:0,period:240,hold:0,impulseX:direction*5.8});selection={type:'addition',index:project.additions.length-1};commit();}
$('add-boost-right').onclick=()=>addBoost(1);$('add-boost-left').onclick=()=>addBoost(-1);
$('randomize').onclick=()=>{if(!project||busy)return;const seed=crypto.getRandomValues(new Uint32Array(1))[0],result=randomizeTargets(project,base,seed);project=result.project;selection=null;commit();toast(`${result.moved} targets moved.${result.locked?' Chest targets stay linked to their chest.':''} Undo restores their positions. Test reachability in Dolphin.`);};
$('add-platform').onclick=()=>add('platform');$('add-bumper').onclick=()=>add('bumper','yellow');

async function allBases(){return Promise.all(catalog.map(c=>get(`/editor/data/${c.stage}.json`)));}
async function collectPack(){
 await save();const drafts={...publishedProjects};
 for(const c of catalog){const raw=await draftStore.get(storageKey(c.stage));if(raw){try{drafts[c.stage]=JSON.parse(raw);}catch{throw Error(`${c.character}: saved draft cannot be read. Export or repair it before building all levels.`);}}}
 if(project)drafts[project.stage]=clone(project);
 const pack=createStagePack(await allBases(),drafts,project?.stage);
 if(new Blob([JSON.stringify(pack)]).size>PACK_LIMIT)throw Error('Level pack must be under 128 MB.');return pack;
}
function downloadPack(pack){const url=URL.createObjectURL(new Blob([JSON.stringify(pack,null,2)+'\n'],{type:'application/json'})),a=el('a');a.href=url;a.download='Custom-Melee-BTT-all-levels.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
async function importDocument(incoming){
 if(incoming?.format!=='TTRC_STAGE_PACK'){
  if(!catalog.some(c=>c.stage===incoming?.stage))throw Error('Unknown stage.');
  await load(incoming.stage,incoming);toast("Imported project. Click Test in Dolphin to play it.");return;
 }
 const errors=validateStagePack(incoming,await allBases());if(errors.length)throw Error(errors.join(' '));
 await save();const previous=new Map();
 try{
  for(const p of incoming.projects){const key=storageKey(p.stage),raw=await draftStore.get(key);previous.set(key,raw);previous.set(key+':older',await draftStore.get(key+':older'));if(raw&&raw!==JSON.stringify(p))await draftStore.set(key+':older',raw);await draftStore.set(key,JSON.stringify(p));}
 }catch(error){for(const [key,raw]of previous){try{if(raw===null)await draftStore.remove(key);else await draftStore.set(key,raw);}catch{}}throw Error('Not enough browser storage to import all levels. Keep the exported file.');}
 project=null;await load(catalog.some(c=>c.stage===incoming.activeStage)?incoming.activeStage:incoming.projects[0].stage);
 toast(`${incoming.projects.length} levels imported. Click Build all in Dolphin to play them.`);
}
async function packAction(button,action){
 if(!project||busy)return;busy=true;const label=button.textContent;button.disabled=true;button.setAttribute('aria-busy','true');button.textContent='Preparing all levels…';
 try{await action(await collectPack());}catch(e){toast(e.message);}finally{busy=false;button.disabled=false;button.removeAttribute('aria-busy');button.textContent=label;checks();}
}
$('export-all').onclick=()=>packAction($('export-all'),async pack=>{downloadPack(pack);toast(`${pack.projects.length} levels exported.`);});
$('build-all').onclick=()=>packAction($('build-all'),async pack=>{
 if(!local){
  const fragment='#draft='+encodeURIComponent(JSON.stringify(pack));
  if(fragment.length>1600000){downloadPack(pack);window.open('http://localhost:4317/editor','_blank','noopener');toast('Open the exported level pack in your companion, then click Build all in Dolphin.');return;}
  window.open('http://localhost:4317/editor'+fragment,'_blank','noopener');toast('All levels sent to your companion. Click Build all in Dolphin there to launch.');return;
 }
 $('build-all').textContent='Building all levels…';
 const r=await fetch('/api/editor/build-all',{method:'POST',headers:{'Content-Type':'application/json','X-TTRC-Action':'launch'},body:JSON.stringify(pack)}),data=await r.json();
 if(!r.ok)throw Error(data.error||'Could not build the level pack.');
 toast(data.status==='already-running'?'Close the Custom Melee BTT game window, then build again.':`${pack.projects.length} levels built. Choose any character in Target Test.`);
});
$('export').onclick=()=>{if(!project)return;const blob=new Blob([JSON.stringify(project,null,2)+'\n'],{type:'application/json'}),url=URL.createObjectURL(blob),a=el('a');a.href=url;a.download=project.name.replace(/[^a-z0-9_-]/gi,'-')+'.ttrc.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('Project exported.');};
$('import').onclick=()=>$('project-file').click();$('project-file').onchange=async()=>{const file=$('project-file').files[0];$('project-file').value='';if(!file)return;if(file.size>PACK_LIMIT)return toast('Project files must be under 128 MB.');try{const p=JSON.parse(await file.text());await importDocument(p);}catch(e){toast(e.message);}};
$('preview').onclick=()=>{if(placingStops!==null)stopPlacement();playing=!playing;$('preview').textContent=playing?'Ⅱ Pause preview':'▶ Preview motion';};$('frame').oninput=()=>{playing=false;frame=Number($('frame').value);$('preview').textContent='▶ Preview motion';draw();};
function tick(now){if(playing&&project){frame=(frame+(now-last)*.06)%Number($('frame').max);draw();}last=now;requestAnimationFrame(tick);}requestAnimationFrame(tick);
document.addEventListener('keydown',e=>{if(['INPUT','TEXTAREA','SELECT'].includes(e.target.tagName))return;if(e.code==='Space'){e.preventDefault();space=true;}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();(e.shiftKey?$('redo'):$('undo')).click();}if(e.key==='Escape'){if(placingStops!==null){stopPlacement();return;}selection=null;renderUI();}if(project&&selection&&['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key)){e.preventDefault();const n=Number($('grid').value)*(e.shiftKey?5:1);moveSelection(project,selection,e.key==='ArrowRight'?n:e.key==='ArrowLeft'?-n:0,e.key==='ArrowUp'?n:e.key==='ArrowDown'?-n:0,base);commit();}});document.addEventListener('keyup',e=>{if(e.code==='Space')space=false;});window.addEventListener('blur',()=>{space=false;release();});
$('test').onclick=async()=>{if(!project||checks().length||busy)return;if(!local){save();const fragment='#draft='+encodeURIComponent(JSON.stringify(project));if(fragment.length>1600000){$('export').click();window.open('http://localhost:4317/editor','_blank','noopener');toast('Project with textures exported. Open that file in your companion, then click Test in Dolphin.');return;}window.open('http://localhost:4317/editor'+fragment,'_blank','noopener');toast('Project sent in the link. In your running companion, click Test in Dolphin to launch it.');return;}busy=true;$('test').disabled=true;$('test').setAttribute('aria-busy','true');$('test').textContent='Building stage…';save();try{const r=await fetch('/api/editor/test',{method:'POST',headers:{'Content-Type':'application/json','X-TTRC-Action':'launch'},body:JSON.stringify(project)});const data=await r.json();if(!r.ok)throw Error(data.error||'Could not build this stage.');toast(data.status==='already-running'?'Close the Custom Melee BTT game window, then test again.':`Dolphin opened. Press Start to play ${base.character}${base.stage==='Sk'?' (hold A for Sheik)':''}.`);}catch(e){toast(e.message);}finally{busy=false;$('test').removeAttribute('aria-busy');$('test').textContent='Test in Dolphin ↗';checks();}};
try{[catalog,additionCatalog]=await Promise.all([get('/editor/data/catalog.json'),get('/editor/data/models/additions.json')]);for(const c of catalog){const option=el('option',c.character+' · '+c.name);option.value=c.stage;$('stage').append(option);}$('stage').disabled=false;try{const r=await fetch('/api/editor/status');if(r.ok){const info=await r.json();local=!!info.available;}}catch{}$('companion-link').hidden=local;if(!local)$('test').title='Transfer this draft to your running local Custom Melee BTT Companion.';const published=await get('/editor/published-levels.json');publishedProjects=Object.fromEntries(published.projects.map(p=>[p.stage,p]));let incoming=null;try{if(location.hash.startsWith('#draft=')){incoming=JSON.parse(decodeURIComponent(location.hash.slice(7)));if(JSON.stringify(incoming).length>8*1024*1024)throw Error('Shared project is too large.');window.history.replaceState(null,'',location.pathname);}}catch(e){toast('Could not open shared project: '+e.message);incoming=null;}let initial=incoming?.stage||'Pk';try{if(!incoming)initial=localStorage.getItem('ttrc-editor-stage')||initial;}catch{}if(incoming)await importDocument(incoming);else await load(catalog.some(c=>c.stage===initial)?initial:'Pk');}catch(e){$('loading').querySelector('p').textContent=e.message;$('retry').hidden=false;$('retry').onclick=()=>location.reload();}

window.addEventListener('hashchange',async()=>{if(!location.hash.startsWith('#draft='))return;try{if(location.hash.length>24000000)throw Error('Shared project is too large.');const incoming=JSON.parse(decodeURIComponent(location.hash.slice(7)));window.history.replaceState(null,'',location.pathname);await importDocument(incoming);}catch(e){toast('Could not open shared project: '+e.message);}});
