import {customSkins,drawMedia,mediaBytes,MEDIA_BUDGET,validateMedia} from './media.js';
import {importMedia} from './media-import.js';
const node=(tag,text)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;return n;};
export function installMediaUI({project,base,selection,commit,add,toast}){
 const panel=document.createElement('details');panel.open=true;panel.className='media-panel';panel.innerHTML='<summary>Background &amp; custom objects</summary><div class="media-buttons"><button id="import-background">Import background</button><button id="create-object">Create textured object</button><button id="apply-texture">Apply texture to selection</button></div><p id="media-memory" class="hint"></p><div id="background-controls"></div><div id="custom-library"></div>';
 document.querySelector('.library').insertBefore(panel,document.querySelector('.palette'));
 const dialog=document.createElement('dialog');dialog.className='media-dialog';dialog.innerHTML=`<form><h2 id="media-title">Import background</h2><label class="field">File<input id="media-file" type="file" accept="image/png,image/jpeg,image/webp,image/gif,video/mp4,video/webm" required></label><p class="hint">PNG, JPG, WebP, GIF, MP4 or WebM. Animated media becomes a silent loop in both the editor and Dolphin.</p><div id="object-options" class="field-grid"><label class="field">Name<input id="media-name" maxlength="80" value="My object" required></label><label class="field">Collision<select id="media-kind"><option value="solid">Solid block</option><option value="platform">One-way platform</option><option value="decoration">Decoration (no collision)</option></select></label><label class="field">Width (stage units)<input id="media-width" type="number" step="any" min="2" max="800" value="64" required></label><label class="field">Height (stage units)<input id="media-height" type="number" step="any" min="2" max="800" value="64" required></label><label class="field wide">Texture mapping<select id="media-mapping"><option value="repeat">Repeat horizontally</option><option value="mirror">Mirror alternating tiles</option><option value="stretch">Fit to object</option></select></label></div><div id="clip-options" class="field-grid" hidden><label class="field">Clip starts at (seconds)<input id="media-start" type="number" min="0" step="0.1" value="0"></label><label class="field">Loop length (seconds)<input id="media-duration" type="number" min="0.1" max="12" step="0.1" value="4"></label></div><label class="field">Maximum texture size<select id="media-resolution"><option value="1024">1024 px · detailed stills</option><option value="512">512 px</option><option value="256">256 px · compact loops</option></select></label><p class="hint">Resolution is fitted to the available 4 MB texture budget. Shorter loops retain more detail. Solid collisions follow the block outline, including transparent parts of the image.</p><p id="media-progress" role="status"></p><div class="media-buttons"><button type="button" id="media-cancel">Cancel</button><button id="media-submit" class="primary">Import</button></div></form>`;
 document.body.append(dialog);const $=id=>document.getElementById(id);let mode='background',controller;
 function open(next){if(!project())return;mode=next;const s=selection();if(mode==='texture'&&!['solid','platform'].includes(s?.type))return toast('Select a solid block or a platform first.');$('media-title').textContent=mode==='background'?'Import background':mode==='texture'?'Apply a texture':'Create a textured object';$('object-options').hidden=mode==='background';$('media-kind').disabled=mode==='texture';$('media-file').value='';$('clip-options').hidden=true;$('media-progress').textContent='';$('media-submit').disabled=false;
  if(mode==='texture'){$('media-kind').value=s.type;if(s.type==='solid'){const pts=project().solids[s.index].points;$('media-width').value=Math.max(2,Math.min(800,Math.max(...pts.map(p=>p[0]))-Math.min(...pts.map(p=>p[0]))));$('media-height').value=Math.max(2,Math.min(800,Math.max(...pts.map(p=>p[1]))-Math.min(...pts.map(p=>p[1]))));}else{$('media-width').value=project().platforms[s.index][2];$('media-height').value=8;}}
  dialog.showModal();
 }
 $('import-background').onclick=()=>open('background');$('create-object').onclick=()=>open('object');$('apply-texture').onclick=()=>open('texture');
 $('media-file').onchange=()=>{const f=$('media-file').files[0];$('clip-options').hidden=!f||!(/\.(gif|mp4|webm)$/i.test(f.name)||f.type.startsWith('video/'));if(f)$('media-name').value=f.name.replace(/\.[^.]+$/,'').slice(0,80);};
 const cancel=()=>{controller?.abort();dialog.close();};$('media-cancel').onclick=cancel;dialog.addEventListener('cancel',()=>controller?.abort());
 dialog.querySelector('form').onsubmit=async e=>{e.preventDefault();if(controller)return;const p=project(),s=selection()?{...selection()}:null;controller=new AbortController();$('media-submit').disabled=true;
  try{
   // Replacing the background may reclaim its old texture if no object uses it.
   const old=p.background?.media,replaceable=mode==='background'&&old&&!(p.customPieces||[]).some(c=>c.media===old),existing=(p.media||[]).filter(m=>!replaceable||m.id!==old);
   const m=await importMedia($('media-file').files[0],{background:mode==='background',start:Number($('media-start').value)||0,duration:Number($('media-duration').value)||4,maxWidth:Number($('media-resolution').value),budget:MEDIA_BUDGET-existing.reduce((n,m)=>n+mediaBytes(m),0),signal:controller.signal,onProgress:v=>$('media-progress').textContent=`Converting frame ${v.current}/${v.total} · ${v.width} × ${v.height}`});
   if(project()!==p)throw Error('The active project changed. Import into the new project again.');
   if(mode==='object'){const kind=$('media-kind').value,count=kind==='solid'?p.solids.length:kind==='platform'?p.platforms.length:(p.decorations||[]).length;if(count>=(kind==='platform'?128:64))throw Error('Remove an object before adding another '+kind+'.');}
   const patch={media:[...existing,m]};
   if(mode==='background')patch.background={media:m.id,bounds:[...(base().backgroundBounds||base().artBounds)]};
   else{const kind=$('media-kind').value,c={id:'custom-'+crypto.randomUUID(),name:$('media-name').value.trim(),kind,media:m.id,width:Number($('media-width').value),height:Number($('media-height').value),mapping:$('media-mapping').value};patch.customPieces=[...(p.customPieces||[]),c];}
   const errors=validateMedia({...p,...patch});if(errors.length)throw Error(errors.join(' '));Object.assign(p,patch);
   if(mode==='texture'){const id=p.customPieces.at(-1).id;if(s.type==='solid')p.solids[s.index].asset=id;else p.platformAssets[s.index]=id;}
   else if(mode==='object')add(p.customPieces.at(-1).id);
   commit();dialog.close();toast(`Imported ${m.width} × ${m.height}${m.frames.length>1?` · ${(m.frames.length*m.frameTicks/60).toFixed(1)}s loop`:''}. Included in project exports and Dolphin builds.`);
  }catch(error){if(error.name!=='AbortError'){$('media-progress').textContent=error.message;toast(error.message);}}finally{controller=null;$('media-submit').disabled=false;}
 };
 function changeBackground(key,value){const p=project();p.background={...p.background,bounds:p.background.bounds.map((v,i)=>i===key?value:v)};commit();}
 function render(){const p=project();if(!p)return;const assets=p.media||[],bytes=assets.reduce((n,m)=>n+mediaBytes(m),0);$('media-memory').textContent=`Imported textures: ${(bytes/1048576).toFixed(2)} / 4 MB`;$('apply-texture').disabled=!['solid','platform'].includes(selection()?.type);
  const controls=$('background-controls');controls.replaceChildren();
  if(p.background){const m=assets.find(m=>m.id===p.background.media);controls.append(node('p',`${m?.name||'Background'} · ${m?.width} × ${m?.height}`));const grid=node('div');grid.className='field-grid';['Left','Top','Right','Bottom'].forEach((label,i)=>{const wrap=node('label',label);wrap.className='field';const input=node('input');input.type='number';input.value=p.background.bounds[i];input.onchange=()=>{const v=Number(input.value);if(Number.isFinite(v))changeBackground(i,v);};wrap.append(input);grid.append(wrap);});controls.append(grid);const fit=node('button','Fit stage');fit.onclick=()=>{p.background={...p.background,bounds:[...base().artBounds]};commit();};const clear=node('button','Restore original background');clear.onclick=()=>{const id=p.background.media;delete p.background;if(!(p.customPieces||[]).some(c=>c.media===id))p.media=p.media.filter(m=>m.id!==id);commit();};controls.append(fit,clear);}
  const library=$('custom-library');library.replaceChildren();for(const c of customSkins(p)){const card=node('div');card.className='custom-piece';const button=node('button');button.className='piece-card';const canvas=node('canvas');canvas.width=160;canvas.height=95;const scale=Math.min(150/c.width,85/c.height);drawMedia(canvas.getContext('2d'),assets.find(m=>m.id===c.media),c.points,([x,y])=>[5+x*scale,5-y*scale],0,c.mapping,c.width);button.append(canvas,node('span',c.name),node('small',c.kind==='decoration'?'Decoration · no collision':c.kind==='solid'?'Solid block':'One-way platform'));button.onclick=()=>{try{add(c.id);commit();}catch(e){toast(e.message);}};const remove=node('button','Remove from library');remove.className='small';remove.onclick=()=>{if(p.solids.some(s=>s.asset===c.id)||p.platformAssets.includes(c.id)||(p.decorations||[]).some(d=>d.piece===c.id))return toast('Remove this object’s placements from the stage first.');p.customPieces=p.customPieces.filter(x=>x.id!==c.id);if(!p.customPieces.some(x=>x.media===c.media)&&p.background?.media!==c.media)p.media=p.media.filter(m=>m.id!==c.media);commit();};card.append(button,remove);library.append(card);}
 }
 return {render};
}
