// Draw the exported native GX geometry and textures, including baked poses.
const surface=document.createElement('canvas');surface.width=surface.height=384;
const gl=surface.getContext('webgl',{alpha:true,premultipliedAlpha:false,preserveDrawingBuffer:true});
let program;const cache=new Map();
if(gl){
 const compile=(type,code)=>{const s=gl.createShader(type);gl.shaderSource(s,code);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS))throw Error(gl.getShaderInfoLog(s));return s;};
 program=gl.createProgram();gl.attachShader(program,compile(gl.VERTEX_SHADER,`attribute vec3 p;attribute vec4 c;attribute vec2 uv;uniform vec4 box;varying vec4 color;varying vec2 st;void main(){gl_Position=vec4((p.x-box.x)/(box.z-box.x)*2.0-1.0,(p.y-box.w)/(box.y-box.w)*2.0-1.0,-p.z/1000.0,1.0);color=c;st=uv;}`));
 gl.attachShader(program,compile(gl.FRAGMENT_SHADER,`precision mediump float;varying vec4 color;varying vec2 st;uniform sampler2D tex;void main(){vec4 q=texture2D(tex,st)*color;if(q.a<0.02)discard;gl_FragColor=q;}`));gl.linkProgram(program);if(!gl.getProgramParameter(program,gl.LINK_STATUS))throw Error(gl.getProgramInfoLog(program));
}
const textures=new Map();
async function texture(spec){const key=JSON.stringify(spec);if(textures.has(key))return textures.get(key);const promise=(async()=>{const t=gl.createTexture();gl.bindTexture(gl.TEXTURE_2D,t);if(spec){const image=await new Promise((resolve,reject)=>{const i=new Image();i.onload=()=>resolve(i);i.onerror=()=>reject(Error('Native texture failed to load'));i.src=spec.url});gl.bindTexture(gl.TEXTURE_2D,t);gl.texImage2D(gl.TEXTURE_2D,0,gl.RGBA,gl.RGBA,gl.UNSIGNED_BYTE,image);const pow2=n=>(n&(n-1))===0;for(const [axis,wrap]of [[gl.TEXTURE_WRAP_S,spec.wrap[0]],[gl.TEXTURE_WRAP_T,spec.wrap[1]]])gl.texParameteri(gl.TEXTURE_2D,axis,pow2(image.width)&&pow2(image.height)?[gl.CLAMP_TO_EDGE,gl.REPEAT,gl.MIRRORED_REPEAT][wrap]||gl.CLAMP_TO_EDGE:gl.CLAMP_TO_EDGE);}else{gl.texImage2D(gl.TEXTURE_2D,0,gl.RGBA,1,1,0,gl.RGBA,gl.UNSIGNED_BYTE,new Uint8Array([255,255,255,255]));}gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MIN_FILTER,gl.LINEAR);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MAG_FILTER,gl.LINEAR);return t})();textures.set(key,promise);return promise;}
export async function loadNative(url){if(!url||!gl)return null;if(cache.has(url))return cache.get(url);const promise=(async()=>{const r=await fetch(url);if(!r.ok)throw Error('Native model failed to load');const model=await r.json();let l=Infinity,t=-Infinity,rr=-Infinity,b=Infinity;for(const pose of model.poses)for(const part of pose){for(const v of part.vertices){l=Math.min(l,v[0]);rr=Math.max(rr,v[0]);t=Math.max(t,v[1]);b=Math.min(b,v[1]);}part.textureGPU=await texture(part.texture);part.buffer=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,part.buffer);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(part.vertices.flat()),gl.STATIC_DRAW);part.count=part.vertices.length;delete part.vertices;}const pad=.1;model.bounds=[l-pad,t+pad,rr+pad,b-pad];return model})();cache.set(url,promise);return promise;}
export function nativeImage(model,frame=0){if(!model||!gl)return null;const pose=model.poses[Math.floor((frame%model.period)/model.period*model.poses.length)]||model.poses[0];gl.viewport(0,0,surface.width,surface.height);gl.clearColor(0,0,0,0);gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);gl.enable(gl.DEPTH_TEST);gl.enable(gl.BLEND);gl.blendFunc(gl.SRC_ALPHA,gl.ONE_MINUS_SRC_ALPHA);gl.useProgram(program);gl.uniform4fv(gl.getUniformLocation(program,'box'),model.bounds);for(const part of pose){gl.bindBuffer(gl.ARRAY_BUFFER,part.buffer);for(const [name,count,offset]of [['p',3,0],['c',4,12],['uv',2,28]]){const loc=gl.getAttribLocation(program,name);gl.enableVertexAttribArray(loc);gl.vertexAttribPointer(loc,count,gl.FLOAT,false,36,offset);}gl.activeTexture(gl.TEXTURE0);gl.bindTexture(gl.TEXTURE_2D,part.textureGPU);gl.uniform1i(gl.getUniformLocation(program,'tex'),0);gl.drawArrays(gl.TRIANGLES,0,part.count);}return surface;}
export function drawNative(ctx,model,x,y,screen,frame=0,scaleX=1,scaleY=1,motionPeriod,rollAngle=null){const im=nativeImage(model,frame);if(!im)return;const [l,t,r,b]=model.bounds,[px,py]=screen([x+l*scaleX,y+t*scaleY]),[rx,ry]=screen([x+r*scaleX,y+b*scaleY]);if(model.rolling&&rollAngle!==null){const [cx,cy]=screen([x+model.rolling.pivot[0]*scaleX,y+model.rolling.pivot[1]*scaleY]);ctx.save();ctx.translate(cx,cy);ctx.rotate(-rollAngle);ctx.drawImage(im,px-cx,py-cy,rx-px,ry-py);ctx.restore();}else if(model.facing){const c=model.facing,t=((frame%(motionPeriod||c.period))/(motionPeriod||c.period))*c.period;let angle=c.keys[0][1];for(let i=1;i<c.keys.length;i++){const [f,v]=c.keys[i];if(t<=f){const [a,b]=c.keys[i-1];angle=b+(v-b)*(t-a)/(f-a);break;}}const [cx,cy]=screen([x+c.pivot[0]*scaleX,y+c.pivot[1]*scaleY]);ctx.save();ctx.translate(cx,cy);ctx.rotate(-angle);ctx.drawImage(im,px-cx,py-cy,rx-px,ry-py);ctx.restore();}else ctx.drawImage(im,px,py,rx-px,ry-py);}
