import {test,expect} from '@playwright/test';
import fs from 'node:fs/promises';
const draft=page=>page.evaluate(async()=>JSON.parse(await(await import('/editor/storage.js')).drafts.get('ttrc-editor-v1:Mr')));
test.beforeEach(async({page})=>{await page.route('**/api/editor/status',r=>r.fulfill({json:{available:true,mediaVersion:1}}));await page.goto('/editor');await expect(page.locator('#loading')).toBeHidden();await page.selectOption('#stage','Mr');await expect(page.locator('#loading')).toBeHidden();});
test('GIF background and textured objects persist, undo, export and compile as embedded media',async({page})=>{
 await page.locator('#import-background').click();await page.locator('#media-file').setInputFiles('test/fixtures/media/loop.gif');await page.locator('#media-submit').click();await expect(page.locator('.media-dialog')).not.toBeVisible();
 let p=await draft(page);expect(p.media[0].frames).toHaveLength(10);expect(p.background.media).toBe(p.media[0].id);
 const colors=await page.evaluate(async()=>{const {mediaImage}=await import('/editor/media.js');const p=JSON.parse(await(await import('/editor/storage.js')).drafts.get('ttrc-editor-v1:Mr'));return [0,30].map(f=>[...mediaImage(p.media[0],f).getContext('2d').getImageData(2,2,1,1).data]);});expect(colors[0][2]).toBeGreaterThan(colors[0][0]);expect(colors[1][0]).toBeGreaterThan(colors[1][2]);
 await page.locator('#create-object').click();await page.locator('#media-file').setInputFiles('test/fixtures/media/tile.png');await page.locator('#media-name').fill('Test bricks');await page.locator('#media-width').fill('40');await page.locator('#media-height').fill('30');await page.locator('#media-submit').click();await expect(page.locator('.media-dialog')).not.toBeVisible();
 p=await draft(page);expect(p.customPieces[0]).toMatchObject({kind:'solid',mapping:'repeat',width:40,height:30});expect(p.solids.at(-1).asset).toBe(p.customPieces[0].id);
 await page.locator('#undo').click();expect((await draft(page)).customPieces).toBeUndefined();await page.locator('#redo').click();expect((await draft(page)).media).toHaveLength(2);
 await page.locator('#create-object').click();await page.locator('#media-file').setInputFiles('test/fixtures/media/tile.png');await page.locator('#media-name').fill('Backdrop object');await page.locator('#media-kind').selectOption('decoration');await page.locator('#media-submit').click();await expect(page.locator('.media-dialog')).not.toBeVisible();
 p=await draft(page);expect(p.decorations).toHaveLength(1);await page.reload();await expect(page.locator('#loading')).toBeHidden();expect(await draft(page)).toEqual(p);
 const pending=page.waitForEvent('download');await page.locator('#export').click();const download=await pending;const exported=JSON.parse(await fs.readFile(await download.path(),'utf8'));expect(exported.media).toEqual(p.media);
 await page.locator('#project-file').setInputFiles(await download.path());await expect(page.locator('#toast')).toContainText('Imported');expect(await draft(page)).toEqual(p);
 let submitted;await page.route('**/api/editor/test',async r=>{submitted=r.request().postDataJSON();await r.fulfill({json:{status:'started'}});});await page.locator('#test').click();await expect(page.locator('#toast')).toContainText('Dolphin opened');expect(submitted.media).toEqual(p.media);
 await fs.mkdir('build/editor-media',{recursive:true});await fs.writeFile('build/editor-media/test-project.json',JSON.stringify(p));await page.screenshot({path:'build/editor-media/editor.png',fullPage:true});
});
test('invalid file and cancelled import leave project unchanged',async({page})=>{
 const before=await draft(page);await page.locator('#import-background').click();await page.locator('#media-file').setInputFiles({name:'bad.png',mimeType:'image/png',buffer:Buffer.from('not a PNG')});await page.locator('#media-submit').click();await expect(page.locator('#media-progress')).not.toBeEmpty();expect(await draft(page)).toEqual(before);await page.locator('#media-cancel').click();expect(await draft(page)).toEqual(before);
});
test('WebM is converted into a timed silent texture loop',async({page})=>{
 const media=await page.evaluate(async()=>{const c=document.createElement('canvas');c.width=64;c.height=64;const ctx=c.getContext('2d'),stream=c.captureStream(10),chunks=[],rec=new MediaRecorder(stream,{mimeType:'video/webm'});const done=new Promise(r=>rec.onstop=r);rec.ondataavailable=e=>chunks.push(e.data);rec.start();for(const color of ['red','blue','green','yellow']){ctx.fillStyle=color;ctx.fillRect(0,0,64,64);await new Promise(r=>setTimeout(r,150));}rec.stop();await done;stream.getTracks().forEach(t=>t.stop());return [...new Uint8Array(await new Blob(chunks,{type:'video/webm'}).arrayBuffer())];});
 await page.locator('#import-background').click();await page.locator('#media-file').setInputFiles({name:'loop.webm',mimeType:'video/webm',buffer:Buffer.from(media)});await page.locator('#media-duration').fill('0.3');await page.locator('#media-submit').click();await expect(page.locator('.media-dialog')).not.toBeVisible();const p=await draft(page);expect(p.media[0].frames.length).toBe(3);expect(p.media[0].frameTicks).toBe(6);
});
test('applying an uploaded texture preserves the selected wall collision',async({page})=>{
 const before=await draft(page);await page.locator('#object-list button[data-type="solid"]').first().click();await page.locator('#apply-texture').click();await page.locator('#media-file').setInputFiles('test/fixtures/media/tile.png');await page.locator('#media-submit').click();await expect(page.locator('.media-dialog')).not.toBeVisible();const p=await draft(page);expect(p.solids[0].points).toEqual(before.solids[0].points);expect(p.solids[0].material).toBe(before.solids[0].material);expect(p.solids[0].asset).toBe(p.customPieces[0].id);expect(p.solids.slice(1)).toEqual(before.solids.slice(1));await page.locator('#undo').click();expect(await draft(page)).toEqual(before);
});
