import { test, expect } from '@playwright/test';

test('admin uses the normal account, schedules reveal and keeps management private', async ({page, browser}) => {
  const errors=[];page.on('pageerror',error=>errors.push(error.message));
  await page.goto('http://localhost:4319');
  await expect(page.locator('#admin-link')).toBeHidden();
  await page.locator('#player-action').click();
  await page.locator('#auth-username').fill('test_admin');
  await page.locator('#auth-password').fill('Admin browser test 42');
  await page.locator('#auth-submit').click();
  await expect(page.getByRole('link',{name:'Admin',exact:true})).toBeVisible();
  await page.locator('#admin-link').click();
  await expect(page.getByRole('heading',{name:'Challenge management'})).toBeVisible();
  await expect(page.locator('#desk')).toBeVisible();await expect(page.locator('#access')).toBeHidden();
  await expect(page.locator('#deadline-summary')).toContainText('No end date');
  const future=new Date(Date.now()+86400000);future.setSeconds(0,0);
  const local=new Date(future.getTime()-future.getTimezoneOffset()*60000).toISOString().slice(0,16);
  await page.locator('#deadline').fill(local);await page.getByRole('button',{name:'Save date'}).click();
  await expect(page.locator('#message')).toContainText('End date saved');
  await page.reload();await expect(page.locator('#deadline')).toHaveValue(local);
  await page.locator('#close').click();await expect(page.locator('#confirm')).toBeVisible();
  await page.locator('#confirm').getByRole('button',{name:'Close',exact:true}).click();
  await expect(page.locator('#phase')).toContainText('OPEN');
  await page.screenshot({path:'build/admin-desktop.png',fullPage:true});
  const guestContext=await browser.newContext(),guest=await guestContext.newPage();
  await guest.goto('http://localhost:4319');await expect(guest.locator('#admin-link')).toBeHidden();
  await expect(guest.locator('#competition-detail')).toContainText('Closes and reveals');
  await guest.goto('http://localhost:4319/review');await expect(guest.locator('#access')).toBeVisible();await expect(guest.locator('#desk')).toBeHidden();
  await guestContext.close();
  await page.getByRole('button',{name:'Remove date'}).click();await expect(page.locator('#deadline-summary')).toContainText('No end date');
  await page.setViewportSize({width:390,height:844});
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  await page.screenshot({path:'build/admin-mobile.png',fullPage:true});
  await page.goto('http://localhost:4319');await page.locator('#logout').click();await expect(page.locator('#admin-link')).toBeHidden();
  await page.goto('http://localhost:4319/review');await expect(page.locator('#desk')).toBeHidden();
  expect(errors).toEqual([]);
});

test('companion shows compact personal bests with expandable replay history', async ({ page }) => {
  const errors=[];page.on('pageerror',e=>errors.push(e.message));
  await page.goto('/');
  await expect(page.getByText('DESKTOP COMPANION')).toBeVisible();
  await expect(page.locator('#seed')).toHaveText('20260989');
  await expect(page.locator('#player-name')).toHaveText('Browser Test');
  await expect(page.locator('#run-list')).toContainText('00:20.57');
  await expect(page.getByText('LIVE SESSION',{exact:true})).toHaveCount(0);
  await expect(page.locator('#peach-items select')).toHaveCount(10);
  await page.locator('#play').click();
  await expect(page.locator('#toast')).toContainText('Dolphin is starting');
  await expect(page.getByText('WATCH YOUR ATTEMPTS',{exact:true})).toHaveCount(0);
  await expect(page.locator('#replay-list')).toHaveCount(0);
  const fox=page.locator('.run-group').filter({has:page.getByRole('button',{name:'Fox: show run history'})});
  await expect(fox.getByRole('button',{name:'Submit',exact:false})).toBeDisabled();
  await expect(page.locator('#run-list > .run-group')).toHaveCount(3);
  await expect(page.locator('#run-list .run')).toHaveCount(3);
  const peach=page.locator('.run-group').filter({has:page.getByRole('button',{name:/^Peach: /})});
  await expect(peach).toContainText('No valid clear');await expect(peach).toContainText('Paused during the run');
  await expect(peach.getByRole('button',{name:'Submit',exact:false})).toHaveCount(0);
  await expect(peach.getByRole('button',{name:'Watch replay'})).toBeEnabled();
  await page.getByRole('button',{name:'Peach: show run history'}).click();
  await expect(peach.locator('.attempt-history .run')).toHaveCount(1);
  await page.getByRole('button',{name:'Peach: hide run history'}).click();
  await page.getByRole('button',{name:'Donkey Kong: show run history'}).click();
  const attempts=page.locator('.attempt-history .run');
  await expect(attempts).toHaveCount(2);
  await expect(attempts.first()).toContainText('00:21.67');
  await attempts.first().getByRole('button',{name:'Watch replay'}).click();
  await expect(page.locator('#toast')).toContainText('Replay opened in Dolphin Playback');
  await page.getByRole('button',{name:'Donkey Kong: hide run history'}).click();
  await expect(page.locator('.attempt-history')).toHaveCount(0);
  await page.locator('#tab-sent').click();
  await expect(page.locator('#empty')).toBeVisible();
  await page.setViewportSize({width:390,height:844});
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  expect(errors).toEqual([]);
});

test('replay goes from companion to private review; public site shows only participants until reveal', async ({ page }) => {
  await page.goto('/');
  const dk=page.locator('.run-group').filter({has:page.getByRole('button',{name:'Donkey Kong: show run history'})});
  const submitted=page.waitForRequest(r=>r.url().endsWith('/api/submissions')&&r.method()==='POST');
  await dk.getByRole('button',{name:'Submit',exact:false}).click();
  expect(Object.keys((await submitted).postDataJSON())).toEqual(['id']);
  await expect(dk).toContainText('Submitted');
  await page.reload();
  await dk.getByRole('button',{name:'Watch replay'}).click();
  await expect(page.locator('#toast')).toContainText('Replay opened in Dolphin Playback');
  const pending=await (await page.request.get('http://localhost:4319/api/dashboard')).json();
  expect(pending.participants.map(p=>p.displayName)).toContain('Browser Test');
  expect(pending.leaderboard).toEqual([]);
  await page.goto('/review');
  await expect(page.locator('#queue')).toContainText('Browser Test');
  await page.getByRole('button',{name:'Launch replay'}).click();
  await expect(page.locator('#message')).toContainText('Replay opened in Dolphin Playback');
  const download=page.waitForEvent('download');
  await page.getByText('Download private .slp ↓').click();
  expect((await download).suggestedFilename()).toMatch(/\.slp$/);
  await page.getByRole('button',{name:'Approve run'}).click();
  await expect(page.locator('#queue')).toContainText('APPROVED');
  await page.goto('http://localhost:4319/?character=donkey-kong');
  await expect(page.locator('#scores')).toContainText('Browser Test');
  await expect(page.locator('#board-title')).toHaveText('Participants');
  await expect(page.locator('thead')).not.toContainText('RANK');
  await expect(page.locator('#scores')).not.toContainText('00:19.83');
  const board=await (await page.request.get('http://localhost:4319/api/dashboard?character=donkey-kong')).json();
  expect(board.leaderboard).toEqual([]);
  expect(board.participants[0].displayName).toBe('Browser Test');
  expect(board.participants[0].rank).toBeUndefined();
  await expect(page.locator('.leaderboard select')).toHaveCount(0);
  const login=await page.request.post('http://localhost:4318/api/remote/browser',{headers:{Origin:'http://localhost:4318','X-TTRC-Action':'profile'}});
  await page.goto((await login.json()).url);await expect(page.locator('#display-name')).toHaveText('Browser Test');
  await page.locator('.record-group summary').getByRole('button',{name:'Disclose run'}).click();
  await expect(page.locator('#disclose-dialog')).toBeVisible();await page.locator('#confirm-disclose').click();
  await expect(page.locator('#shared-list')).toContainText('Browser Test');
  const guestContext=await page.context().browser().newContext(),guest=await guestContext.newPage();
  await guest.goto('http://localhost:4319');await expect(guest.locator('#shared-list')).toContainText('00:19.83');
  await expect(guest.locator('#history-list')).toBeEmpty();
  const evidence=await guest.locator('#shared-list a[download]').getAttribute('href');
  expect((await guest.request.get('http://localhost:4319'+evidence)).status()).toBe(200);
  const playbackLink=await guest.getByRole('link',{name:'Watch in Dolphin'}).getAttribute('href');
  await guest.goto(playbackLink.replace(':4317',':4318'));await expect(guest.locator('#shared-summary')).toContainText('Browser Test');
  await guest.locator('#shared-launch').click();await expect(guest.locator('#toast')).toContainText('Replay opened in Dolphin Playback');
  await page.locator('.record-group summary').getByRole('button',{name:'Make private'}).click();
  await expect(page.locator('#shared-list')).toBeEmpty();expect((await guest.request.get('http://localhost:4319'+evidence)).status()).toBe(404);
  await guestContext.close();
  await page.goto('http://localhost:4318/review');
  await page.locator('#close').click();await page.locator('#confirm-close').click();
  await expect(page.locator('#phase')).toContainText('CLOSED');
  await page.goto('http://localhost:4319/?character=donkey-kong');
  await expect(page.locator('#board-title')).toHaveText('Leaderboard');
  await expect(page.locator('#scores')).toContainText('00:19.83');
  await expect(page.locator('thead')).toContainText('RANK');
  await page.setViewportSize({width:390,height:844});
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
});

test('Unique username and password connect the companion without email or file downloads', async ({ page, context }) => {
  const errors = []; page.on('pageerror', e => errors.push(e.message));
  await page.goto('http://localhost:4319');
  await expect(page.locator('#player-action')).toHaveText('Sign in');
  await expect(page.locator('input[type=file]')).toHaveCount(0);
  await page.locator('#create-account').click();
  await expect(page.locator('input[type=email]')).toHaveCount(0);
  await page.locator('#auth-username').fill('Browser_Player');
  await page.locator('#auth-password').fill('Browser test password 42');
  await page.locator('#auth-submit').click();
  await expect(page.locator('#connect-code')).toHaveText('@browser_player');
  await page.locator('#connect-code').click();
  await expect(page.locator('#public-name')).toHaveText('@browser_player');
  await page.goto('http://localhost:4318');
  await page.locator('#sign-out').click();
  await expect(page.locator('#player-name')).toHaveText('Not signed in');
  const popupEvent = context.waitForEvent('page'); await page.locator('#sign-in').click();
  const popup = await popupEvent; await popup.waitForLoadState();
  await expect(popup.locator('#connect-verification')).toHaveText(await page.locator('#account-code').innerText());
  await popup.locator('#approve-companion').click();
  await expect(popup.locator('#connect-status')).toContainText('Connected');
  await expect(page.locator('#player-code')).toHaveText('@browser_player');
  await expect(page.locator('#account-connection')).not.toBeVisible();
  const dashboard = await (await page.request.get('http://localhost:4318/api/dashboard')).json();
  expect(JSON.stringify(dashboard)).not.toContain('token');
  await popup.close();
  await page.goto('http://localhost:4319'); await page.locator('#logout').click();
  await expect(page.locator('#player-action')).toHaveText('Sign in');
  await page.locator('#player-action').click();
  await page.locator('#auth-username').fill('BROWSER_PLAYER');
  await page.locator('#auth-password').fill('Browser test password 42');
  await page.locator('#auth-submit').click();
  await expect(page.locator('#connect-code')).toHaveText('@browser_player');
  await expect(page.locator('#auth-dialog')).not.toBeVisible();
  await page.setViewportSize({ width: 390, height: 844 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  expect(errors).toEqual([]);
});

test('website groups all submitted runs, retains old bests and exports the full history',async({page})=>{
  const errors=[];page.on('pageerror',e=>errors.push(e.message));
  await page.route('**/api/dashboard?*',async route=>{
    const response=await route.fetch(),body=await response.json();
    body.identity={id:'test-history',displayName:'History Test',connectCode:'TT#1'};body.player={id:'test-history'};
    body.history=Array.from({length:62},(_,i)=>({id:`history-${i}`,character:i<60?'fox':'marth',stage:i<60?'samus':'mewtwo',frames:i===0?600:1200+i,createdAt:new Date(1700000000000+i*1000).toISOString(),status:'pending'})).reverse();
    await route.fulfill({response,json:body});
  });
  await page.goto('http://localhost:4319');
  await expect(page.locator('#history-count')).toHaveText('2 characters · 62 submitted runs');
  await expect(page.locator('#history-list details')).toHaveCount(2);
  const fox=page.locator('.record-group[data-character="fox"]');
  await expect(fox.locator('summary')).toContainText('00:10.00');
  await fox.locator('summary').click();await expect(fox.locator('.history-row')).toHaveCount(60);
  await expect(fox.locator('.history-row').last()).toContainText('00:10.00');
  await page.getByRole('button',{name:'Marth → Mewtwo',exact:true}).click();
  await expect(page.locator('#personal-character')).toHaveText('MARTH');
  await expect(fox).toHaveAttribute('open','');await expect(page.locator('#history-list details')).toHaveCount(2);
  const downloaded=page.waitForEvent('download');await page.locator('#export-runs').click();
  const file=await downloaded,stream=await file.createReadStream();let csv='';for await(const part of stream)csv+=part;
  expect(file.suggestedFilename()).toContain('all-runs');expect(csv.trim().split('\n')).toHaveLength(63);
  await page.setViewportSize({width:390,height:844});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  expect(errors).toEqual([]);
});

test('companion saves music and rumble independently and restores them on reload',async({page})=>{
 let running=false;
 await page.route('**/api/dashboard',async route=>{const response=await route.fetch(),body=await response.json();body.capture={...body.capture,native:true,replayEnabled:true,dolphinRunning:running};await route.fulfill({response,json:body});});
 await page.goto('/');
 const music=page.getByRole('checkbox',{name:'Game music'}),rumble=page.getByRole('checkbox',{name:'Controller rumble'});
 await expect(music).toBeEnabled();await expect(music).toBeChecked();await expect(rumble).toBeChecked();
 await music.uncheck();await expect(music).toBeEnabled();await expect(rumble).toBeChecked();
 await page.reload();await expect(music).toBeEnabled();await expect(music).not.toBeChecked();await expect(rumble).toBeChecked();
 await rumble.uncheck();await expect(rumble).toBeEnabled();
 await page.reload();await expect(rumble).toBeEnabled();await expect(rumble).not.toBeChecked();await expect(music).not.toBeChecked();
 await expect(page.locator('#settings-note')).toContainText('next time you launch Dolphin');
 await expect(page.getByRole('button',{name:'Launch Dolphin'})).toBeVisible();
 running=true;await page.reload();await expect(page.locator('#settings-note')).toContainText('close and relaunch Dolphin');
 await music.check();await expect(music).toBeEnabled();await rumble.check();await expect(rumble).toBeEnabled();
});

test('fresh companion shows ISO onboarding and reveals play controls only after setup',async({page})=>{
 let setup={ready:false,busy:false,isoReady:false,step:'iso',message:'Choose your Melee ISO to get started.'};
 await page.route('**/api/dashboard',async route=>{const response=await route.fetch(),data=await response.json();await route.fulfill({json:{...data,setup}});});
 await page.route('**/api/setup/install',async route=>{setup={...setup,busy:true,isoReady:true,message:'Downloading Dolphin for playing…',progress:25};await route.fulfill({status:202,json:setup});});
 await page.goto('/');await expect(page.getByRole('heading',{name:'Set up Melee'})).toBeVisible();
 await expect(page.getByRole('button',{name:'Choose Melee ISO',exact:true})).toBeVisible();
 await expect(page.getByRole('button',{name:'Launch Dolphin'})).not.toBeVisible();
 await page.getByRole('button',{name:'Set up Dolphin',exact:true}).click();
 await expect(page.locator('#setup-message')).toContainText('Downloading Dolphin');
 await expect(page.getByRole('button',{name:'Choose another ISO'})).toBeDisabled();
 setup={...setup,ready:true,busy:false};await page.reload();
 await expect(page.locator('#setup-panel')).not.toBeVisible();await expect(page.getByRole('button',{name:'Launch Dolphin'})).toBeVisible();
});


test('character options persist with UCF and per-target Peach items',async({page})=>{
 await page.goto('/');await expect(page.getByRole('checkbox',{name:'UCF',exact:true})).toBeChecked();
 await page.locator('.character-settings summary').click();
 const nana=page.getByRole('checkbox',{name:'Ice Climbers: play with Nana'}),misfire=page.getByRole('checkbox',{name:'Luigi: always misfire'});
 await nana.check();await expect(nana).toBeEnabled();await misfire.check();await expect(misfire).toBeEnabled();
 await page.getByLabel('Peach item with 10 targets left',{exact:true}).selectOption('beam-sword');await expect(nana).toBeEnabled();
 await page.getByLabel('Peach item with 9 targets left',{exact:true}).selectOption('bob-omb');await expect(nana).toBeEnabled();
 await page.reload();await page.locator('.character-settings summary').click();
 await expect(nana).toBeChecked();await expect(misfire).toBeChecked();await expect(page.getByRole('checkbox',{name:'UCF',exact:true})).toBeChecked();
 await expect(page.getByLabel('Peach item with 10 targets left',{exact:true})).toHaveValue('beam-sword');
 await expect(page.getByLabel('Peach item with 9 targets left',{exact:true})).toHaveValue('bob-omb');
 await expect(page.getByLabel('Peach item with 1 targets left',{exact:true})).toHaveValue('random');
 await page.getByRole('button',{name:'Reset to random'}).click();await expect(nana).toBeEnabled();
 for(const select of await page.locator('#peach-items select').all())await expect(select).toHaveValue('random');
 await expect(nana).toBeChecked();await expect(misfire).toBeChecked();
 await page.setViewportSize({width:390,height:844});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
});

// Motion belongs to the challenge and is visible without a local gameplay toggle.
test('seeded target mix is explained in the companion and on the website',async({page})=>{
 await page.goto('http://localhost:4318');
 await expect(page.locator('#motion-note')).toContainText('6–10 fixed');
 await page.goto('http://localhost:4319');
 await expect(page.locator('#target-behavior')).toHaveText('Seeded mix');
 await expect(page.locator('#course-grid')).toContainText('teleporting');
});

test('Remove GO and Fixed camera save independently and survive reload',async({page})=>{
 await page.goto('/');
 const go=page.getByRole('checkbox',{name:'Remove GO',exact:true}),camera=page.getByRole('checkbox',{name:'Fixed camera',exact:true});
 await expect(go).toBeEnabled();await expect(go).not.toBeChecked();await expect(camera).not.toBeChecked();
 await go.check();await expect(go).toBeEnabled();await camera.check();await expect(camera).toBeEnabled();
 await page.reload();await expect(go).toBeChecked();await expect(camera).toBeChecked();
 await go.uncheck();await expect(go).toBeEnabled();await page.reload();await expect(go).not.toBeChecked();await expect(camera).toBeChecked();
 await camera.uncheck();await expect(camera).toBeEnabled();
});

 test('public website drops course tools and ignores old focus and favorites preferences',async({page})=>{
  const errors=[];page.on('pageerror',error=>errors.push(error.message));
  await page.addInitScript(()=>{localStorage.setItem('ttrc-focus','true');localStorage.setItem('ttrc-favorites','["fox"]');});
  await page.goto('http://localhost:4319');
  await expect(page.locator('#course-grid .course-card')).toHaveCount(25);
  for(const label of ['Random course','Favorite','Share challenge','Focus mode','Selected course','Favorites only'])await expect(page.getByText(label,{exact:false})).toHaveCount(0);
  await expect(page.locator('.sidebar')).toBeVisible();
  await page.keyboard.press('f');await page.keyboard.press('r');
  await expect(page.locator('body')).not.toHaveClass(/focus-mode/);
  await page.locator('#course-search').fill('Marth');await expect(page.locator('#course-grid')).toContainText('Marth');
  expect(errors).toEqual([]);
});

test('challenge deadline is prominent, ticks, and waits for server-confirmed reveal',async({page})=>{
  const errors=[];page.on('pageerror',error=>errors.push(error.message));
  const now=new Date('2026-09-27T12:00:00Z');
  await page.clock.install({time:now});
  let phase={phase:'open',timesRevealed:false,endsAt:'2026-09-29T15:04:05Z',closedAt:null};
  await page.route('**/api/dashboard?*',async route=>{const response=await route.fetch(),body=await response.json();await route.fulfill({response,json:{...body,competition:phase}});});
  await page.goto('http://localhost:4319');
  await expect(page.locator('#deadline-countdown')).toHaveText('2d 03h 04m 05s');
  await expect(page.locator('#deadline-date')).toHaveAttribute('datetime',phase.endsAt.replace('Z','.000Z'));
  await expect(page.locator('#deadline-date')).toContainText('September 29, 2026');
  await expect(page.locator('#deadline-admin')).toBeHidden();
  const banner=await page.locator('.challenge-deadline').boundingBox(),hero=await page.locator('.hero').boundingBox();expect(banner.y+banner.height).toBeLessThan(hero.y);
  await page.clock.fastForward(2000);await expect(page.locator('#deadline-countdown')).toHaveText('2d 03h 04m 03s');
  await page.setViewportSize({width:390,height:844});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  await page.screenshot({path:'build/deadline-mobile.png',fullPage:false});
  phase={...phase,endsAt:'2026-09-27T12:00:01Z'};await page.reload();
  await expect(page.locator('#deadline-countdown')).toHaveText('Closing…');
  await expect(page.locator('#competition-state')).toHaveText('Results hidden');
  phase={...phase,phase:'closed',timesRevealed:true,closedAt:phase.endsAt};await page.reload();
  await expect(page.locator('#deadline-label')).toHaveText('Challenge ended');
  await expect(page.locator('#deadline-countdown')).toHaveText('Results revealed');
  phase={phase:'open',timesRevealed:false,endsAt:null,closedAt:null};await page.reload();
  await expect(page.locator('#deadline-countdown')).toHaveText('No end date set');await expect(page.locator('#deadline-date')).toBeHidden();
  expect(errors).toEqual([]);
});
