import { test, expect } from '@playwright/test';

test('admin uses the normal account, schedules reveal and keeps management private', async ({page, browser}) => {
  const errors=[];page.on('pageerror',error=>errors.push(error.message));
  await page.goto('http://localhost:4319');
  await expect(page.locator('#admin-link')).toBeHidden();
  await page.locator('#player-action').click();
  await page.locator('#auth-username').fill('test_admin');
  await page.locator('#auth-password').fill('Admin browser test 42');
  await page.locator('#auth-submit').click();
  await expect(page.getByRole('link',{name:'Admin',exact:true})).toBeVisible();
  await page.locator('#admin-link').click();
  await expect(page.getByRole('heading',{name:'Challenge management'})).toBeVisible();
  await expect(page.locator('#desk')).toBeVisible();await expect(page.locator('#access')).toBeHidden();
  await expect(page.locator('#deadline-summary')).toContainText('No end date');
  const future=new Date(Date.now()+86400000);future.setSeconds(0,0);
  const local=new Date(future.getTime()-future.getTimezoneOffset()*60000).toISOString().slice(0,16);
  await page.locator('#deadline').fill(local);await page.getByRole('button',{name:'Save date'}).click();
  await expect(page.locator('#message')).toContainText('End date saved');
  await page.reload();await expect(page.locator('#deadline')).toHaveValue(local);
  await page.locator('#close').click();await expect(page.locator('#confirm')).toBeVisible();
  await page.locator('#confirm').getByRole('button',{name:'Close',exact:true}).click();
  await expect(page.locator('#phase')).toContainText('OPEN');
  await page.screenshot({path:'build/admin-desktop.png',fullPage:true});
  const guestContext=await browser.newContext(),guest=await guestContext.newPage();
  await guest.goto('http://localhost:4319');await expect(guest.locator('#admin-link')).toBeHidden();
  await expect(guest.locator('#competition-detail')).toContainText('Closes and reveals');
  await guest.goto('http://localhost:4319/review');await expect(guest.locator('#access')).toBeVisible();await expect(guest.locator('#desk')).toBeHidden();
  await guestContext.close();
  await page.getByRole('button',{name:'Remove date'}).click();await expect(page.locator('#deadline-summary')).toContainText('No end date');
  await page.setViewportSize({width:390,height:844});
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  await page.screenshot({path:'build/admin-mobile.png',fullPage:true});
  await page.goto('http://localhost:4319');await page.locator('#logout').click();await expect(page.locator('#admin-link')).toBeHidden();
  await page.goto('http://localhost:4319/review');await expect(page.locator('#desk')).toBeHidden();
  expect(errors).toEqual([]);
});

test('companion shows compact personal bests with expandable replay history', async ({ page }) => {
  const errors=[];page.on('pageerror',e=>errors.push(e.message));
  await page.goto('/');
  await expect(page.getByText('DESKTOP COMPANION')).toBeVisible();
  await expect(page.locator('#seed')).toHaveText('20260989');
  await expect(page.locator('#player-name')).toHaveText('Browser Test');
  await expect(page.locator('#run-list')).toContainText('00:20.57');
  await expect(page.getByText('LIVE SESSION',{exact:true})).toHaveCount(0);
  await expect(page.locator('#peach-items select')).toHaveCount(10);
  await page.locator('#play').click();
  await expect(page.locator('#toast')).toContainText('Dolphin is starting');
  await expect(page.getByText('WATCH YOUR ATTEMPTS',{exact:true})).toHaveCount(0);
  await expect(page.locator('#replay-list')).toHaveCount(0);
  const fox=page.locator('.run-group').filter({has:page.getByRole('button',{name:'Fox: show run history'})});
  await expect(fox.getByRole('button',{name:'Submit',exact:false})).toBeDisabled();
  await expect(page.locator('#run-list > .run-group')).toHaveCount(3);
  await expect(page.locator('#run-list .run')).toHaveCount(3);
  const peach=page.locator('.run-group').filter({has:page.getByRole('button',{name:/^Peach: /})});
  await expect(peach).toContainText('No valid clear');await expect(peach).toContainText('Paused during the run');
  await expect(peach.getByRole('button',{name:'Submit',exact:false})).toHaveCount(0);
  await expect(peach.getByRole('button',{name:'Watch replay'})).toBeEnabled();
  await page.getByRole('button',{name:'Peach: show run history'}).click();
  await expect(peach.locator('.attempt-history .run')).toHaveCount(1);
  await page.getByRole('button',{name:'Peach: hide run history'}).click();
  await page.getByRole('button',{name:'Donkey Kong: show run history'}).click();
  const attempts=page.locator('.attempt-history .run');
  await expect(attempts).toHaveCount(2);
  await expect(attempts.first()).toContainText('00:21.67');
  await attempts.first().getByRole('button',{name:'Watch replay'}).click();
  await expect(page.locator('#toast')).toContainText('Replay opened in Dolphin Playback');
  await page.getByRole('button',{name:'Donkey Kong: hide run history'}).click();
  await expect(page.locator('.attempt-history')).toHaveCount(0);
  await page.locator('#tab-sent').click();
  await expect(page.locator('#empty')).toBeVisible();
  await page.setViewportSize({width:390,height:844});
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  expect(errors).toEqual([]);
});

test('replay goes from companion to private review; public site shows only participants until reveal', async ({ page }) => {
  await page.goto('/');
  const dk=page.locator('.run-group').filter({has:page.getByRole('button',{name:'Donkey Kong: show run history'})});
  const submitted=page.waitForRequest(r=>r.url().endsWith('/api/submissions')&&r.method()==='POST');
  await dk.getByRole('button',{name:'Submit',exact:false}).click();
  expect(Object.keys((await submitted).postDataJSON())).toEqual(['id']);
  await expect(dk).toContainText('Submitted');
  await page.reload();
  await dk.getByRole('button',{name:'Watch replay'}).click();
  await expect(page.locator('#toast')).toContainText('Replay opened in Dolphin Playback');
  const pending=await (await page.request.get('http://localhost:4319/api/dashboard')).json();
  expect(pending.participants.map(p=>p.displayName)).toContain('Browser Test');
  expect(pending.leaderboard).toEqual([]);
  await dk.getByRole('button',{name:'Share Donkey Kong run'}).click();
  await page.getByRole('button',{name:'Share score',exact:true}).click();
  await expect(page.locator('#share-status')).toContainText('Score shared');
  let publicScore=await (await page.request.get('http://localhost:4319/api/dashboard')).json();
  expect(publicScore.sharedRuns[0].hasReplay).toBe(false);
  expect((await page.request.get(`http://localhost:4319/api/shared/replay?id=${publicScore.sharedRuns[0].id}&playerId=${publicScore.sharedRuns[0].playerId}`)).status()).toBe(404);
  await page.getByRole('button',{name:'Share replay',exact:true}).click();
  await expect(page.locator('#share-status')).toContainText('Score and replay shared');
  await page.getByRole('button',{name:'Make private',exact:true}).click();
  await expect(page.locator('#share-status')).toContainText('Disclosure removed');
  await page.getByRole('button',{name:'Close sharing'}).click();
  await page.goto('/review');
  await expect(page.locator('#queue')).toContainText('Browser Test');
  await page.getByRole('button',{name:'Launch replay'}).click();
  await expect(page.locator('#message')).toContainText('Replay opened in Dolphin Playback');
  const download=page.waitForEvent('download');
  await page.getByText('Download private .slp ↓').click();
  expect((await download).suggestedFilename()).toMatch(/\.slp$/);
  await expect(page.getByRole('button',{name:'Approve run'})).toHaveCount(0);
  await expect(page.getByRole('button',{name:'Exclude run'})).toHaveCount(0);
  await expect(page.locator('#queue')).toContainText('SUBMITTED');
  await page.goto('http://localhost:4319/?character=donkey-kong');
  await expect(page.locator('#scores')).toContainText('Browser Test');
  await expect(page.locator('#board-title')).toHaveText('Participants');
  await expect(page.locator('.leaderboard thead')).not.toContainText('RANK');
  await expect(page.locator('#scores')).not.toContainText('00:19.83');
  const board=await (await page.request.get('http://localhost:4319/api/dashboard?character=donkey-kong')).json();
  expect(board.leaderboard).toEqual([]);
  expect(board.participants[0].displayName).toBe('Browser Test');
  expect(board.participants[0].rank).toBeUndefined();
  await expect(page.locator('.leaderboard select')).toHaveCount(0);
  const login=await page.request.post('http://localhost:4318/api/remote/browser',{headers:{Origin:'http://localhost:4318','X-TTRC-Action':'profile'}});
  await page.goto((await login.json()).url);await expect(page.locator('#display-name')).toHaveText('Browser Test');
  const manage=()=>page.locator('.record-group summary').getByRole('button',{name:'Manage Donkey Kong disclosure'});
  await manage().click();
  await expect(page.locator('#disclose-dialog')).toBeVisible();await page.getByRole('button',{name:'Disclose score',exact:true}).click();
  await expect(page.locator('#shared-list')).toContainText('Score only');
  let scoreBoard=await(await page.request.get('http://localhost:4319/api/dashboard')).json();
  expect(scoreBoard.history[0].disclosureKind).toBe('score');
  const scoreReplay=`http://localhost:4319/api/shared/replay?id=${scoreBoard.history[0].id}&playerId=${scoreBoard.player.id}`;
  expect((await page.request.get(scoreReplay)).status()).toBe(404);
  await page.reload();await expect(manage()).toContainText('Score public');
  await manage().click();await expect(page.locator('#disclose-status')).toContainText('replay private');
  await page.getByRole('button',{name:'Disclose replay',exact:true}).click();
  await expect(manage()).toContainText('Replay public');expect((await page.request.get(scoreReplay)).status()).toBe(200);
  await manage().click();await page.getByRole('button',{name:'Disclose score',exact:true}).click();
  await expect(manage()).toContainText('Score public');expect((await page.request.get(scoreReplay)).status()).toBe(404);
  await manage().click();await page.getByRole('button',{name:'Disclose replay',exact:true}).click();
  await expect(page.locator('#shared-list')).toContainText('Browser Test');
  const guestContext=await page.context().browser().newContext(),guest=await guestContext.newPage();
  await guest.goto('http://localhost:4319');await expect(guest.locator('#shared-list')).toContainText('00:19.83');
  await expect(guest.locator('#history-list')).toBeEmpty();
  const evidence=await guest.locator('#shared-list a[download]').getAttribute('href');
  expect((await guest.request.get('http://localhost:4319'+evidence)).status()).toBe(200);
  const fighter=guest.getByRole('button',{name:'Donkey Kong → Donkey Kong',exact:true});await fighter.scrollIntoViewIfNeeded();
  const scroll=await guest.evaluate(()=>scrollY);await fighter.click();
  await expect(guest.locator('#character-dialog')).toBeVisible();await expect(guest.locator('#character-title')).toHaveText('Donkey Kong');
  await expect(guest.locator('#character-replays')).toContainText('Browser Test');
  expect(Math.abs(await guest.evaluate(()=>scrollY)-scroll)).toBeLessThan(5);
  const playbackLink=await guest.locator('#character-replays').getByRole('link',{name:'Watch in Dolphin'}).getAttribute('href');
  await guest.goto(playbackLink.replace(':4317',':4318'));await expect(guest.locator('#shared-summary')).toContainText('Browser Test');
  await guest.locator('#shared-launch').click();await expect(guest.locator('#toast')).toContainText('Replay opened in Dolphin Playback');
  await manage().click();await page.getByRole('button',{name:'Make private',exact:true}).click();
  await expect(page.locator('#shared-list')).toBeEmpty();expect((await guest.request.get('http://localhost:4319'+evidence)).status()).toBe(404);
  await guestContext.close();
  await page.goto('http://localhost:4318/review');
  await page.locator('#close').click();await page.locator('#confirm-close').click();
  await expect(page.locator('#phase')).toContainText('CLOSED');
  await page.goto('http://localhost:4319/?character=donkey-kong');
  await expect(page.locator('#board-title')).toHaveText('Leaderboard');
  await expect(page.locator('.record-group summary')).toContainText('Score and replay public after reveal');
  await expect(manage()).toHaveCount(0);
  await page.locator('#scores').getByRole('button',{name:'Browser Test',exact:true}).click();
  await expect(page.locator('#points-total')).toContainText('10 points');
  await expect(page.locator('#points-ths')).toContainText('THS incomplete');
  await expect(page.locator('#points-courses')).toContainText('00:19.83');
  await page.getByRole('button',{name:'Close points breakdown'}).click();
  await page.getByRole('button',{name:'Total High Score',exact:true}).click();
  await expect(page.locator('#board-empty')).toContainText('No complete THS yet');
  await page.getByRole('button',{name:'Overall points',exact:true}).click();
  await expect(page.locator('.leaderboard thead')).toContainText('RANK');
  await page.getByRole('link',{name:'Old challenges',exact:true}).click();
  await expect(page.locator('#current-challenge-view')).toBeHidden();
  const archive=page.locator('.archive-card');await expect(archive).toHaveCount(1);
  await expect(archive).toContainText('Your place');await expect(archive).toContainText('#1 of 1');
  await expect(archive).toContainText('Start date');await expect(archive).toContainText('Not recorded');await expect(archive).toContainText('End date');
  await archive.locator('summary').click();await expect(archive.locator('tbody')).toContainText('Browser Test');
  const gecko=await(await page.request.get('http://localhost:4319/api/challenge/code')).text();
  await expect(archive.locator('textarea')).toHaveValue(gecko);
  await page.context().grantPermissions(['clipboard-read','clipboard-write']);
  await archive.getByRole('button',{name:'Copy Gecko code'}).click();
  expect(await page.evaluate(()=>navigator.clipboard.readText())).toBe(gecko);
  await archive.getByRole('button',{name:'Total High Score',exact:true}).click();await expect(archive).toContainText('No player completed all characters.');
  await archive.getByRole('button',{name:'Overall points',exact:true}).click();
  await page.setViewportSize({width:390,height:844});
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  await page.screenshot({path:'build/archives-mobile.png',fullPage:true});
  await archive.getByRole('link',{name:'Open challenge & replays'}).click();
  await expect(page.locator('#old-challenges')).toBeHidden();await expect(page.locator('#competition-state')).toHaveText('Challenge closed');
});

test('Unique username and password connect the companion without email or file downloads', async ({ page, context }) => {
  const errors = []; page.on('pageerror', e => errors.push(e.message));
  await page.goto('http://localhost:4319');
  await expect(page.locator('#player-action')).toHaveText('Sign in');
  await expect(page.locator('input[type=file]')).toHaveCount(0);
  await page.locator('#create-account').click();
  await expect(page.locator('input[type=email]')).toHaveCount(0);
  await page.locator('#auth-username').fill('Browser_Player');
  await page.locator('#auth-password').fill('Browser test password 42');
  await page.locator('#auth-submit').click();
  await expect(page.locator('#connect-code')).toHaveText('@browser_player');
  await page.locator('#connect-code').click();
  await expect(page.locator('#public-name')).toHaveText('@browser_player');
  await page.goto('http://localhost:4318');
  await page.locator('#sign-out').click();
  await expect(page.locator('#player-name')).toHaveText('Not signed in');
  const popupEvent = context.waitForEvent('page'); await page.locator('#sign-in').click();
  const popup = await popupEvent; await popup.waitForLoadState();
  await expect(popup.locator('#connect-verification')).toHaveText(await page.locator('#account-code').innerText());
  await popup.locator('#approve-companion').click();
  await expect(popup.locator('#connect-status')).toContainText('Connected');
  await expect(page.locator('#player-code')).toHaveText('@browser_player');
  await expect(page.locator('#account-connection')).not.toBeVisible();
  const dashboard = await (await page.request.get('http://localhost:4318/api/dashboard')).json();
  expect(JSON.stringify(dashboard)).not.toContain('token');
  await popup.close();
  await page.goto('http://localhost:4319'); await page.locator('#logout').click();
  await expect(page.locator('#player-action')).toHaveText('Sign in');
  await page.locator('#player-action').click();
  await page.locator('#auth-username').fill('BROWSER_PLAYER');
  await page.locator('#auth-password').fill('Browser test password 42');
  await page.locator('#auth-submit').click();
  await expect(page.locator('#connect-code')).toHaveText('@browser_player');
  await expect(page.locator('#auth-dialog')).not.toBeVisible();
  await page.setViewportSize({ width: 390, height: 844 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  expect(errors).toEqual([]);
});

test('website groups all submitted runs, retains old bests and exports the full history',async({page})=>{
  const errors=[];page.on('pageerror',e=>errors.push(e.message));
  await page.route('**/api/dashboard?*',async route=>{
    const response=await route.fetch(),body=await response.json();
    body.identity={id:'test-history',displayName:'History Test',connectCode:'TT#1'};body.player={id:'test-history'};
    body.history=Array.from({length:62},(_,i)=>({id:`history-${i}`,character:i<60?'fox':'marth',stage:i<60?'samus':'mewtwo',frames:i===0?600:1200+i,createdAt:new Date(1700000000000+i*1000).toISOString(),status:'pending'})).reverse();
    await route.fulfill({response,json:body});
  });
  await page.goto('http://localhost:4319');
  await expect(page.locator('#history-count')).toHaveText('2 characters · 62 submitted runs');
  await expect(page.locator('#history-list details')).toHaveCount(2);
  const fox=page.locator('.record-group[data-character="fox"]');
  await expect(fox.locator('summary')).toContainText('00:10.00');
  await fox.locator('summary').click();await expect(fox.locator('.history-row')).toHaveCount(60);
  await expect(fox.locator('.history-row').last()).toContainText('00:10.00');
  await page.getByRole('button',{name:'Marth → Mewtwo',exact:true}).click();
  await expect(page.locator('#character-title')).toHaveText('Marth');
  await expect(fox).toHaveAttribute('open','');await expect(page.locator('#history-list details')).toHaveCount(2);
  await expect(page.locator('#character-dialog')).toBeVisible();
  await page.getByRole('button',{name:'Close character details'}).click();
  const downloaded=page.waitForEvent('download');await page.locator('#export-runs').click();
  const file=await downloaded,stream=await file.createReadStream();let csv='';for await(const part of stream)csv+=part;
  expect(file.suggestedFilename()).toContain('all-runs');expect(csv.trim().split('\n')).toHaveLength(63);
  await page.setViewportSize({width:390,height:844});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  expect(errors).toEqual([]);
});

test('companion saves music and rumble independently and restores them on reload',async({page})=>{
 let running=false;
 await page.route('**/api/dashboard',async route=>{const response=await route.fetch(),body=await response.json();body.capture={...body.capture,native:true,replayEnabled:true,dolphinRunning:running};await route.fulfill({response,json:body});});
 await page.goto('/');
 const music=page.getByRole('checkbox',{name:'Game music'}),rumble=page.getByRole('checkbox',{name:'Controller rumble'});
 await expect(music).toBeEnabled();await expect(music).toBeChecked();await expect(rumble).toBeChecked();
 await music.uncheck();await expect(music).toBeEnabled();await expect(rumble).toBeChecked();
 await page.reload();await expect(music).toBeEnabled();await expect(music).not.toBeChecked();await expect(rumble).toBeChecked();
 await rumble.uncheck();await expect(rumble).toBeEnabled();
 await page.reload();await expect(rumble).toBeEnabled();await expect(rumble).not.toBeChecked();await expect(music).not.toBeChecked();
 await expect(page.locator('#settings-note')).toContainText('next time you launch Dolphin');
 await expect(page.getByRole('button',{name:'Launch Dolphin'})).toBeVisible();
 running=true;await page.reload();await expect(page.locator('#settings-note')).toContainText('close and relaunch Dolphin');
 await music.check();await expect(music).toBeEnabled();await rumble.check();await expect(rumble).toBeEnabled();
});

test('fresh companion shows ISO onboarding and reveals play controls only after setup',async({page})=>{
 let setup={ready:false,busy:false,isoReady:false,step:'iso',message:'Choose your Melee ISO to get started.'};
 await page.route('**/api/dashboard',async route=>{const response=await route.fetch(),data=await response.json();await route.fulfill({json:{...data,setup}});});
 await page.route('**/api/setup/install',async route=>{setup={...setup,busy:true,isoReady:true,message:'Downloading Dolphin for playing…',progress:25};await route.fulfill({status:202,json:setup});});
 await page.goto('/');await expect(page.getByRole('heading',{name:'Set up Melee'})).toBeVisible();
 await expect(page.getByRole('button',{name:'Choose Melee ISO',exact:true})).toBeVisible();
 await expect(page.getByRole('button',{name:'Launch Dolphin'})).not.toBeVisible();
 await page.getByRole('button',{name:'Set up Dolphin',exact:true}).click();
 await expect(page.locator('#setup-message')).toContainText('Downloading Dolphin');
 await expect(page.getByRole('button',{name:'Choose another ISO'})).toBeDisabled();
 setup={...setup,ready:true,busy:false};await page.reload();
 await expect(page.locator('#setup-panel')).not.toBeVisible();await expect(page.getByRole('button',{name:'Launch Dolphin'})).toBeVisible();
});


test('character options persist with UCF and per-target Peach items',async({page})=>{
 await page.goto('/');await expect(page.getByRole('checkbox',{name:'UCF',exact:true})).toBeChecked();
 await page.locator('.character-settings summary').click();
 const nana=page.getByRole('checkbox',{name:'Ice Climbers: play with Nana'}),misfire=page.getByRole('checkbox',{name:'Luigi: always misfire'});
 await nana.check();await expect(nana).toBeEnabled();await misfire.check();await expect(misfire).toBeEnabled();
 await page.getByLabel('Peach item with 10 targets left',{exact:true}).selectOption('beam-sword');await expect(nana).toBeEnabled();
 await page.getByLabel('Peach item with 9 targets left',{exact:true}).selectOption('bob-omb');await expect(nana).toBeEnabled();
 await page.reload();await page.locator('.character-settings summary').click();
 await expect(nana).toBeChecked();await expect(misfire).toBeChecked();await expect(page.getByRole('checkbox',{name:'UCF',exact:true})).toBeChecked();
 await expect(page.getByLabel('Peach item with 10 targets left',{exact:true})).toHaveValue('beam-sword');
 await expect(page.getByLabel('Peach item with 9 targets left',{exact:true})).toHaveValue('bob-omb');
 await expect(page.getByLabel('Peach item with 1 targets left',{exact:true})).toHaveValue('random');
 await page.getByRole('button',{name:'Reset to random'}).click();await expect(nana).toBeEnabled();
 for(const select of await page.locator('#peach-items select').all())await expect(select).toHaveValue('random');
 await expect(nana).toBeChecked();await expect(misfire).toBeChecked();
 await page.setViewportSize({width:390,height:844});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
});

// Motion belongs to the challenge and is visible without a local gameplay toggle.
test('seeded target mix is explained in the companion and on the website',async({page})=>{
 await page.goto('http://localhost:4318');
 await expect(page.locator('#motion-note')).toContainText('6–10 fixed');
 await page.goto('http://localhost:4319');
 await expect(page.locator('#target-behavior')).toHaveText('Seeded mix');
 await expect(page.locator('#course-grid')).toContainText('teleporting');
});

test('Remove GO and Fixed camera save independently and survive reload',async({page})=>{
 await page.goto('/');
 const go=page.getByRole('checkbox',{name:'Remove GO',exact:true}),camera=page.getByRole('checkbox',{name:'Fixed camera',exact:true});
 await expect(go).toBeEnabled();await expect(go).not.toBeChecked();await expect(camera).not.toBeChecked();
 await go.check();await expect(go).toBeEnabled();await camera.check();await expect(camera).toBeEnabled();
 await page.reload();await expect(go).toBeChecked();await expect(camera).toBeChecked();
 await go.uncheck();await expect(go).toBeEnabled();await page.reload();await expect(go).not.toBeChecked();await expect(camera).toBeChecked();
 await camera.uncheck();await expect(camera).toBeEnabled();
});

 test('public website drops course tools and ignores old focus and favorites preferences',async({page})=>{
  const errors=[];page.on('pageerror',error=>errors.push(error.message));
  await page.addInitScript(()=>{localStorage.setItem('ttrc-focus','true');localStorage.setItem('ttrc-favorites','["fox"]');});
  await page.goto('http://localhost:4319');
  await expect(page.locator('#course-grid .course-card')).toHaveCount(25);
  for(const label of ['Random course','Favorite','Share challenge','Focus mode','Selected course','Favorites only'])await expect(page.getByText(label,{exact:false})).toHaveCount(0);
  await expect(page.locator('.sidebar')).toBeVisible();
  await page.keyboard.press('f');await page.keyboard.press('r');
  await expect(page.locator('body')).not.toHaveClass(/focus-mode/);
  await page.locator('#course-search').fill('Marth');await expect(page.locator('#course-grid')).toContainText('Marth');
  expect(errors).toEqual([]);
});

test('challenge deadline is prominent, ticks, and waits for server-confirmed reveal',async({page})=>{
  const errors=[];page.on('pageerror',error=>errors.push(error.message));
  const now=new Date('2026-09-27T12:00:00Z');
  await page.clock.install({time:now});
  let phase={phase:'open',timesRevealed:false,endsAt:'2026-09-29T15:04:05Z',closedAt:null};
  await page.route('**/api/dashboard?*',async route=>{const response=await route.fetch(),body=await response.json();await route.fulfill({response,json:{...body,competition:phase}});});
  await page.goto('http://localhost:4319');
  await expect(page.locator('#deadline-countdown')).toHaveText('2d 03h 04m 05s');
  await expect(page.locator('#deadline-date')).toHaveAttribute('datetime',phase.endsAt.replace('Z','.000Z'));
  await expect(page.locator('#deadline-date')).toContainText('September 29, 2026');
  await expect(page.locator('#deadline-admin')).toBeHidden();
  const banner=await page.locator('.challenge-deadline').boundingBox(),hero=await page.locator('.hero').boundingBox();expect(banner.y+banner.height).toBeLessThan(hero.y);
  await page.clock.fastForward(2000);await expect(page.locator('#deadline-countdown')).toHaveText('2d 03h 04m 03s');
  await page.setViewportSize({width:390,height:844});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  await page.screenshot({path:'build/deadline-mobile.png',fullPage:false});
  phase={...phase,endsAt:'2026-09-27T12:00:01Z'};await page.reload();
  await expect(page.locator('#deadline-countdown')).toHaveText('Closing…');
  await expect(page.locator('#competition-state')).toHaveText('Results hidden');
  phase={...phase,phase:'closed',timesRevealed:true,closedAt:phase.endsAt};await page.reload();
  await expect(page.locator('#deadline-label')).toHaveText('Challenge ended');
  await expect(page.locator('#deadline-countdown')).toHaveText('Results revealed');
  phase={phase:'open',timesRevealed:false,endsAt:null,closedAt:null};await page.reload();
  await expect(page.locator('#deadline-countdown')).toHaveText('No end date set');await expect(page.locator('#deadline-date')).toBeHidden();
  expect(errors).toEqual([]);
});

test('admin generates a fresh seed and the previous challenge remains accessible',async({page})=>{
 const origin='http://localhost:4319';
 await page.request.post(origin+'/api/auth/login',{headers:{Origin:origin},data:{username:'test_admin',password:'Admin browser test 42'}});
 const before=await(await page.request.get(origin+'/api/dashboard')).json();
 await page.request.post(origin+'/api/review/close',{headers:{Origin:origin},data:{challengeId:before.challenge.id,confirm:'REVEAL'}});
 await page.goto(origin+'/review');
 await expect(page.getByRole('button',{name:'Approve run'})).toHaveCount(0);await expect(page.getByRole('button',{name:'Exclude run'})).toHaveCount(0);
 await page.locator('#new-seed').fill('20261012');await page.locator('#generate-button').click();
 await expect(page.locator('#generate-confirm')).toBeVisible();await page.locator('#publish-challenge').click();
 await expect(page.locator('#phase')).toContainText('20261012');await expect(page.locator('#phase')).toContainText('OPEN');
 await expect(page.locator('#generate-button')).toBeDisabled();
 await page.goto(origin);await expect(page.locator('#seed')).toHaveText('20261012');await page.locator('#challenge-archives summary').click();
 await page.getByRole('link',{name:`Seed ${before.challenge.rules.seed}`,exact:true}).click();
 await expect(page.locator('#seed')).toHaveText(String(before.challenge.rules.seed));await expect(page.locator('#competition-state')).toHaveText('Challenge closed');
});

test('old challenges prompt guests to sign in and show an empty state for nonparticipants',async({page})=>{
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('http://localhost:4319/#old-challenges');
 await expect(page.locator('#old-challenges-message')).toContainText('Sign in');
 await expect(page.locator('#old-challenges-list')).toBeEmpty();
 await page.locator('#old-challenges-signin').click();
 await page.locator('#auth-username').fill('test_admin');await page.locator('#auth-password').fill('Admin browser test 42');
 await page.locator('#auth-submit').click();
 await expect(page.locator('#old-challenges-message')).toContainText('No finished challenges yet');
 await expect(page.locator('#old-challenges-link')).toHaveAttribute('aria-current','page');
 await page.setViewportSize({width:390,height:844});
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 await page.reload();await expect(page.locator('#old-challenges-message')).toContainText('No finished challenges yet');
 await page.getByRole('link',{name:'Current challenge',exact:true}).click();
 await expect(page.locator('#current-challenge-view')).toBeVisible();
 await page.locator('#logout').click();await page.getByRole('link',{name:'Old challenges',exact:true}).click();
 await expect(page.locator('#old-challenges-message')).toContainText('Sign in');
 expect(errors).toEqual([]);
});

function requestGate(){let release;const wait=new Promise(resolve=>{release=resolve;});return {wait,release};}

test('website shows skeletons during slow loads and clears them after a character error',async({page})=>{
 const origin='http://localhost:4319',base=await(await page.request.get(origin+'/api/dashboard')).json();
 base.competition={...base.competition,timesRevealed:true,phase:'closed'};
 let gate=requestGate(),fail=false;
 await page.route('**/api/dashboard?**',async route=>{await gate.wait;const character=new URL(route.request().url()).searchParams.get('character');await route.fulfill({status:fail?503:200,json:fail?{error:'Unavailable'}:{...base,character}});});
 await page.goto(origin,{waitUntil:'commit'});
 await expect(page.locator('#scores .loading-skeleton')).toBeVisible();await expect(page.locator('#loading-status')).toContainText('Loading challenge');
 gate.release();await expect(page.locator('#scores')).not.toHaveAttribute('aria-busy','true');await expect(page.locator('#loading-status')).toBeHidden();
 gate=requestGate();fail=true;
 await page.locator('[data-character="samus"]').click();
 await expect(page.locator('#character-results .loading-skeleton')).toBeVisible();await expect(page.locator('#character-results')).toHaveAttribute('aria-busy','true');
 gate.release();await expect(page.locator('#character-results-note')).toContainText('Could not refresh');
 await expect(page.locator('#character-results .loading-skeleton')).toHaveCount(0);await expect(page.locator('#loading-status')).toBeHidden();
 await page.getByRole('button',{name:'Close character details'}).click();
 fail=false;await page.locator('[data-character="samus"]').click();await expect(page.locator('#character-results-note')).toContainText('No submitted results');
 await page.getByRole('button',{name:'Close character details'}).click();
 // Polling updates cached data without putting the whole page back into a loading state.
 const poll=page.waitForResponse(r=>r.url().includes('/api/dashboard?'));
 await poll;await expect(page.locator('#loading-status')).toBeHidden();
});

test('companion shows attempt skeletons, busy replay buttons and recovers from launch failure',async({page})=>{
 const base=await(await page.request.get('http://localhost:4318/api/dashboard')).json();
 const run={id:'loading-test',character:'fox',stage:'samus',frames:1234,createdAt:new Date().toISOString(),submissionStatus:'submitted',hasReplay:true,attemptCount:1};
 base.bestRuns=[run];base.history=[run];
 await page.route('**/api/dashboard',route=>route.fulfill({json:base}));
 let historyGate=requestGate();
 await page.route('**/api/runs?**',async route=>{await historyGate.wait;await route.fulfill({json:{runs:[run]}});});
 await page.goto('http://localhost:4318');await page.getByRole('button',{name:'Fox: show run history'}).click();
 await expect(page.locator('.attempt-history .loading-skeleton')).toBeVisible();await expect(page.locator('.attempt-history')).toHaveAttribute('aria-busy','true');
 historyGate.release();await expect(page.locator('.attempt-history .run')).toHaveCount(1);await expect(page.locator('.attempt-history .loading-skeleton')).toHaveCount(0);
 const launchGate=requestGate();let launches=0;
 await page.route('**/api/runs/replay/launch',async route=>{launches++;await launchGate.wait;await route.fulfill({status:503,json:{error:'Playback unavailable. Try again.'}});});
 const watch=page.locator('.attempt-history').getByRole('button',{name:'Watch replay'});await watch.click();
 await expect(watch).toHaveAttribute('aria-busy','true');await expect(watch).toBeDisabled();
 await watch.evaluate(el=>el.dispatchEvent(new MouseEvent('click',{bubbles:true})));expect(launches).toBe(1);
 await expect(page.locator('#loading-status')).toContainText('Opening replay');
 launchGate.release();await expect(page.locator('#toast')).toContainText('Playback unavailable');await expect(watch).toBeEnabled();await expect(watch).not.toHaveAttribute('aria-busy','true');await expect(page.locator('#loading-status')).toBeHidden();
});

test('admin shows initial and refresh skeletons and stops loading on an API error',async({page})=>{
 const origin='http://localhost:4319';
 await page.request.post(origin+'/api/auth/login',{headers:{Origin:origin},data:{username:'test_admin',password:'Admin browser test 42'}});
 const queue=await(await page.request.get(origin+'/api/review/queue')).json();
 let gate=requestGate(),fail=false;
 await page.route('**/api/review/queue',async route=>{await gate.wait;await route.fulfill({status:fail?503:200,json:fail?{error:'Temporary connection failure'}:queue});});
 await page.goto(origin+'/review',{waitUntil:'commit'});await expect(page.locator('#admin-loading .loading-skeleton')).toBeVisible();
 gate.release();await expect(page.locator('#desk')).toBeVisible();await expect(page.locator('#admin-loading')).toBeHidden();
 gate=requestGate();fail=true;await page.locator('#refresh').click();
 await expect(page.locator('#refresh')).toHaveAttribute('aria-busy','true');await expect(page.locator('#queue .loading-skeleton')).toBeVisible();
 gate.release();await expect(page.locator('#message')).toContainText('Temporary connection failure');
 await expect(page.locator('#refresh')).not.toHaveAttribute('aria-busy','true');await expect(page.locator('#loading-status')).toBeHidden();await expect(page.locator('#desk')).toBeHidden();
});

test('companion counts aborted attempts separately from finishes and updates an open history',async({page})=>{
 const base=await(await page.request.get('http://localhost:4318/api/dashboard')).json();
 const finished={id:'finished-fox',character:'fox',stage:base.challenge.assignments.fox,frames:600,createdAt:new Date().toISOString(),submissionStatus:'submitted',hasReplay:true,attemptStatus:'finished'};
 const aborted={id:'aborted-fox',...finished,frames:null,hasReplay:false,attemptStatus:'aborted',abortReason:'Reset or changed run'};aborted.id='aborted-fox';
 const running={...aborted,id:'active-fox',attemptStatus:'active',abortReason:''};
 const marth={...aborted,id:'aborted-marth',character:'marth',stage:base.challenge.assignments.marth};
 const counts={fox:{total:3,finished:1,aborted:1,interrupted:0,active:1},marth:{total:2,finished:0,aborted:2,interrupted:0,active:0}};
 base.bestRuns=[{...finished,attemptCount:3,finishedCount:1},{...marth,attemptCount:2,finishedCount:0}];base.history=[finished];
 base.attempts={total:5,finished:1,aborted:3,interrupted:0,active:1,byCharacter:counts};
 await page.route('**/api/dashboard',route=>route.fulfill({json:base}));
 await page.route('**/api/runs?**',route=>route.fulfill({json:{runs:new URL(route.request().url()).searchParams.get('character')==='fox'?[running,aborted,finished]:[marth,{...marth,id:'old-marth'}]}}));
 await page.goto('http://localhost:4318');await expect(page.locator('#total-attempts')).toHaveText('5');await expect(page.locator('#finished-attempts')).toHaveText('1');
 await expect(page.locator('#active-attempts')).toHaveText('1 in progress');
 const fox=page.locator('.run-group').filter({has:page.getByRole('button',{name:'Fox: show run history'})});
 await expect(fox).toContainText('3 total attempts · 1 finished');
 await page.getByRole('button',{name:'Fox: show run history'}).click();await expect(page.locator('.attempt-history .run')).toHaveCount(3);
 const unfinished=page.locator('.attempt-history .run').filter({has:page.locator('.badge').filter({hasText:/^(Aborted|In progress)$/})});
 await expect(unfinished).toHaveCount(2);await expect(unfinished.getByRole('button')).toHaveCount(0);
 running.attemptStatus='aborted';running.abortReason='Left the course';counts.fox.active=0;counts.fox.aborted=2;base.attempts.active=0;base.attempts.aborted=4;
 await expect(page.locator('#active-attempts')).toBeEmpty();
 await expect(page.locator('.attempt-history .badge').filter({hasText:'In progress'})).toHaveCount(0);
 await expect(page.locator('.attempt-history .badge').filter({hasText:'Aborted'})).toHaveCount(2);
 await page.getByRole('button',{name:'Marth: show run history'}).click();
 const group=page.locator('.run-group').filter({has:page.getByRole('button',{name:'Marth: hide run history'})});
 await expect(group).toContainText('No completed run');await expect(group).toContainText('2 total attempts · 0 finished');await expect(group.getByRole('button',{name:'Watch replay'})).toHaveCount(0);
 await page.setViewportSize({width:390,height:844});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 await page.screenshot({path:'build/attempts-mobile.png',fullPage:true});
 await page.locator('#tab-sent').click();await expect(page.locator('#run-list > .run-group')).toHaveCount(1);await expect(page.locator('#total-attempts')).toHaveText('5');
});

test('companion shows download progress, deferred installation, errors and automatic version reload',async({page})=>{
 let state={supported:true,currentVersion:'0.9.0',version:'0.10.0',phase:'downloading',progress:42},checks=0,loads=0;
 page.on('load',()=>loads++);
 await page.route('**/api/dashboard',async route=>{const response=await route.fetch();const d=await response.json();d.appUpdate=state;await route.fulfill({json:d});});
 await page.route('**/api/app-update/check',async route=>{checks++;state={...state,phase:'checking'};await route.fulfill({status:202,json:state});});
 await page.goto('/');await expect(page.locator('#app-version')).toHaveText('TTRC 0.9.0');await expect(page.locator('#app-update-message')).toContainText('42%');await expect(page.locator('#app-update-progress')).toHaveAttribute('value','42');await expect(page.locator('#check-app-update')).toBeDisabled();
 state={...state,phase:'ready'};await expect(page.locator('#app-update-message')).toContainText('when Dolphin is closed');
 state={...state,phase:'error',error:'Download failed. You can keep playing.'};await expect(page.locator('#check-app-update')).toBeEnabled();await page.locator('#check-app-update').click();expect(checks).toBe(1);await expect(page.locator('#app-update-message')).toContainText('Checking');
 state={...state,phase:'installing'};await expect(page.locator('#app-update-message')).toContainText('reconnect automatically');await expect(page.locator('#play')).toBeDisabled();
 const oldLoads=loads;state={...state,currentVersion:'0.10.0',phase:'current'};await expect.poll(()=>loads).toBeGreaterThan(oldLoads);await expect(page.locator('#app-version')).toHaveText('TTRC 0.10.0');await expect(page.locator('#app-update-message')).toContainText('Up to date');
 await page.setViewportSize({width:390,height:844});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
});
